-- US backend baseline: extensions
-- GENERATED by scripts/build-supabase-baseline.mjs from the committed
-- production capture (docs/us-2.0/F2A_1_PRODUCTION_CAPTURE*.json).
-- Do not edit by hand: regenerate. Never applied to production by F2A.1.
-- Production extensions (F2A b09). On Supabase these are platform-managed;
-- the rebuild test provides equivalents in its platform skeleton instead.

create schema if not exists extensions;
create extension if not exists pg_cron with schema pg_catalog version '1.6.4';
create extension if not exists pg_net with schema extensions version '0.20.4';
create extension if not exists pg_stat_statements with schema extensions version '1.11';
create extension if not exists pgcrypto with schema extensions version '1.3';
create extension if not exists supabase_vault with schema vault version '0.3.1';
create extension if not exists "uuid-ossp" with schema extensions version '1.1';
