-- US backend baseline: types
-- GENERATED by scripts/build-supabase-baseline.mjs from the committed
-- production capture (docs/us-2.0/F2A_1_PRODUCTION_CAPTURE*.json).
-- Do not edit by hand: regenerate. Never applied to production by F2A.1.
-- Standalone composite, enum and domain types.

set check_function_bodies = off;
select pg_catalog.set_config('search_path', '"\$user", public, extensions', false);

create type private.game_v2_candidate as (
  candidate_key text,
  family text,
  mechanic text,
  answer_kind text,
  question_text text,
  predict_text text,
  options jsonb,
  depth smallint,
  topic text,
  source_type text,
  source_ref text,
  recipe_id text,
  recipe_version integer,
  source_question_id uuid,
  source_version integer,
  context jsonb,
  cooldown_class text,
  base_score integer,
  score integer,
  cooled boolean,
  last_played timestamp with time zone
);
