-- US backend baseline: tables
-- GENERATED by scripts/build-supabase-baseline.mjs from the committed
-- production capture (docs/us-2.0/F2A_1_PRODUCTION_CAPTURE*.json).
-- Do not edit by hand: regenerate. Never applied to production by F2A.1.
-- Columns, primary keys, unique and exclusion constraints.
-- CHECK and FOREIGN KEY constraints follow in 40_constraints.sql.

set check_function_bodies = off;
select pg_catalog.set_config('search_path', '"\$user", public, extensions', false);

create table private.game_swipe_v1_catalog (
  id text not null,
  version integer not null,
  question_text text not null,
  options jsonb not null,
  topic text not null,
  active boolean not null,
  created_at timestamp with time zone not null
);
comment on table private.game_swipe_v1_catalog is 'Swipe V1 curated binary-choice cards. Private server-only catalog; materialized into immutable Game V2 session items.';
alter table only private.game_swipe_v1_catalog add constraint game_swipe_v1_catalog_pkey PRIMARY KEY (id);

create table private.left_for_you_cleanup_queue (
  item_id uuid not null,
  couple_id uuid not null,
  sender_id uuid not null,
  kind text not null,
  media_path text,
  claimed_at timestamp with time zone,
  source_deleted_at timestamp with time zone,
  completed_at timestamp with time zone
);
alter table only private.left_for_you_cleanup_queue add constraint left_for_you_cleanup_queue_pkey PRIMARY KEY (item_id);

create table public.activity (
  id uuid not null,
  couple_id uuid not null,
  actor_id uuid,
  type text not null,
  payload jsonb not null,
  created_at timestamp with time zone not null
);
alter table only public.activity add constraint activity_pkey PRIMARY KEY (id);

create table public.bond_quest_templates (
  key text not null,
  title text not null,
  category text not null,
  rarity text not null,
  xp smallint not null,
  mode text not null,
  active boolean not null,
  created_at timestamp with time zone not null
);
alter table only public.bond_quest_templates add constraint bond_quest_templates_pkey PRIMARY KEY (key);

create table public.bond_weekly_quests (
  id uuid not null,
  couple_id uuid not null,
  week_start date not null,
  slot smallint not null,
  template_key text not null,
  title text not null,
  category text not null,
  rarity text not null,
  xp smallint not null,
  confirmed_by uuid[] not null,
  completed_at timestamp with time zone,
  created_at timestamp with time zone not null
);
alter table only public.bond_weekly_quests add constraint bond_weekly_quests_pkey PRIMARY KEY (id);
alter table only public.bond_weekly_quests add constraint bond_weekly_quests_couple_id_week_start_slot_key UNIQUE (couple_id, week_start, slot);
alter table only public.bond_weekly_quests add constraint bond_weekly_quests_couple_week_template_key UNIQUE (couple_id, week_start, template_key);

create table public.bond_weekly_state (
  couple_id uuid not null,
  week_start date not null,
  rerolls_used smallint not null,
  created_at timestamp with time zone not null
);
alter table only public.bond_weekly_state add constraint bond_weekly_state_pkey PRIMARY KEY (couple_id, week_start);

create table public.bucket_items (
  id uuid not null,
  couple_id uuid not null,
  created_by uuid not null,
  title text not null,
  completed boolean not null,
  completed_at timestamp with time zone,
  created_at timestamp with time zone not null,
  note text,
  link_url text,
  status text not null,
  calendar_entry_id uuid,
  updated_at timestamp with time zone not null,
  lived_proposed_by uuid,
  lived_proposed_at timestamp with time zone
);
alter table only public.bucket_items add constraint bucket_items_pkey PRIMARY KEY (id);

create table public.calendar_entries (
  id uuid not null,
  couple_id uuid not null,
  entry_type text not null,
  owner_id uuid,
  created_by uuid not null,
  title text not null,
  description text,
  location text,
  is_all_day boolean not null,
  starts_at timestamp with time zone,
  ends_at timestamp with time zone,
  start_date date,
  end_date date,
  visibility text not null,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null
);
alter table only public.calendar_entries add constraint calendar_entries_pkey PRIMARY KEY (id);

create table public.calendar_reminders (
  id uuid not null,
  couple_id uuid not null,
  entry_id uuid not null,
  recipient_id uuid not null,
  offset_minutes integer not null,
  requested_by uuid not null,
  created_at timestamp with time zone not null,
  sent_at timestamp with time zone
);
alter table only public.calendar_reminders add constraint calendar_reminders_pkey PRIMARY KEY (id);
alter table only public.calendar_reminders add constraint calendar_reminders_entry_recipient_offset_unique UNIQUE (entry_id, recipient_id, offset_minutes);

create table public.conserva_contributions (
  id uuid not null,
  couple_id uuid not null,
  source_item_id uuid not null,
  source_sender_id uuid not null,
  conserved_by uuid not null,
  created_at timestamp with time zone not null
);
alter table only public.conserva_contributions add constraint conserva_contributions_pkey PRIMARY KEY (id);
alter table only public.conserva_contributions add constraint conserva_source_item_unique UNIQUE (source_item_id);

create table public.couple_invites (
  id uuid not null,
  couple_id uuid not null,
  role text not null,
  code_hash text not null,
  used_by uuid,
  used_at timestamp with time zone,
  created_at timestamp with time zone not null
);
alter table only public.couple_invites add constraint couple_invites_pkey PRIMARY KEY (id);
alter table only public.couple_invites add constraint couple_invites_code_hash_key UNIQUE (code_hash);
alter table only public.couple_invites add constraint couple_invites_couple_id_role_key UNIQUE (couple_id, role);

create table public.couple_locations (
  user_id uuid not null,
  couple_id uuid not null,
  latitude double precision not null,
  longitude double precision not null,
  accuracy_m double precision,
  updated_at timestamp with time zone not null
);
alter table only public.couple_locations add constraint couple_locations_pkey PRIMARY KEY (user_id);

create table public.couple_progression_preferences (
  couple_id uuid not null,
  frame_reward_id text,
  theme_reward_id text,
  effect_reward_id text,
  updated_by uuid,
  updated_at timestamp with time zone not null,
  accent_reward_id text,
  badge_reward_id text,
  sticker_reward_id text,
  ring_reward_id text
);
alter table only public.couple_progression_preferences add constraint couple_progression_preferences_pkey PRIMARY KEY (couple_id);

create table public.couple_questions (
  id uuid not null,
  couple_id uuid not null,
  author_role text not null,
  create_request_id uuid not null,
  question_text text not null,
  answer_kind text not null,
  options jsonb not null,
  version integer not null,
  archived_at timestamp with time zone,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  origin text not null,
  week_start date,
  families text[] not null
);
alter table only public.couple_questions add constraint couple_questions_pkey PRIMARY KEY (id);
alter table only public.couple_questions add constraint couple_questions_couple_id_author_role_create_request_id_key UNIQUE (couple_id, author_role, create_request_id);

create table public.couple_reward_unlocks (
  couple_id uuid not null,
  reward_id text not null,
  unlocked_at timestamp with time zone not null
);
alter table only public.couple_reward_unlocks add constraint couple_reward_unlocks_pkey PRIMARY KEY (couple_id, reward_id);

create table public.couples (
  id uuid not null,
  name text not null,
  started_on date not null,
  created_at timestamp with time zone not null,
  home_photo_path text,
  bond_xp integer not null
);
alter table only public.couples add constraint couples_pkey PRIMARY KEY (id);

create table public.daily_answers (
  id uuid not null,
  question_id uuid not null,
  user_id uuid not null,
  couple_id uuid not null,
  answer text not null,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null
);
alter table only public.daily_answers add constraint daily_answers_pkey PRIMARY KEY (id);
alter table only public.daily_answers add constraint daily_answers_question_id_user_id_key UNIQUE (question_id, user_id);

create table public.daily_question_keepsakes (
  id uuid not null,
  couple_id uuid not null,
  source_kind text not null,
  question_id uuid not null,
  source_key text generated always as (((source_kind || ':'::text) || (question_id)::text)) stored,
  question_text text not null,
  question_date date not null,
  francesco_answer text not null,
  beatrice_answer text not null,
  revealed_at timestamp with time zone not null,
  kept_by_role text not null,
  kept_at timestamp with time zone not null
);
comment on table public.daily_question_keepsakes is 'M12B.4: a revealed Daily Question exchange explicitly kept by one partner (Living Archive). Server-written snapshot via keep_daily_question; same-couple read; immutable.';
comment on column public.daily_question_keepsakes.source_key is 'Canonical source identity daily_question:<daily_questions.id>, unique per couple (M12B.3 kind:ref convention).';
comment on column public.daily_question_keepsakes.revealed_at is 'When the reveal opened: the latest answer creation time of the couple for this question, read after the reveal gate.';
alter table only public.daily_question_keepsakes add constraint daily_question_keepsakes_pkey PRIMARY KEY (id);
alter table only public.daily_question_keepsakes add constraint daily_question_keepsakes_one_per_couple_question UNIQUE (couple_id, question_id);

create table public.daily_question_outcomes (
  id uuid not null,
  couple_id uuid not null,
  question_id uuid not null,
  author_role text not null,
  body text not null,
  revision integer not null,
  last_operation_id uuid not null,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null
);
comment on table public.daily_question_outcomes is 'M3-only post-reveal Daily Question reflections; ownership is couple + stable role so claim_us_role re-pair preserves data.';
comment on column public.daily_question_outcomes.author_role is 'Stable relationship role, intentionally not a profile or auth UID; claim_us_role changes UID without changing this ownership.';
alter table only public.daily_question_outcomes add constraint daily_question_outcomes_pkey PRIMARY KEY (id);
alter table only public.daily_question_outcomes add constraint daily_question_outcomes_couple_id_question_id_author_role_key UNIQUE (couple_id, question_id, author_role);

create table public.daily_question_reveal_states (
  couple_id uuid not null,
  question_id uuid not null,
  actor_role text not null,
  reaction text,
  reveal_seen_at timestamp with time zone,
  notice_dismissed_at timestamp with time zone,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null
);
comment on table public.daily_question_reveal_states is 'M10.2: per-person (couple + role) Daily reveal receipt, dismissed-notice flag and reaction to the partner answer. RPC-only access.';
alter table only public.daily_question_reveal_states add constraint daily_question_reveal_states_pkey PRIMARY KEY (couple_id, question_id, actor_role);

create table public.daily_question_templates (
  id text not null,
  weekday_slot smallint not null,
  sequence smallint not null,
  question text not null,
  theme text not null,
  active boolean not null,
  created_at timestamp with time zone not null
);
comment on table public.daily_question_templates is 'M9E curated Daily Question bank. Server-only: no client grants, RLS forced with no policies. Rows are materialized into public.daily_questions by private.materialize_daily_question.';
comment on column public.daily_question_templates.weekday_slot is 'ISO weekday (1 = Monday … 7 = Sunday) of the Europe/Rome day this family belongs to.';
comment on column public.daily_question_templates.sequence is 'Editorial order inside the weekday family (week of the 26-week cycle).';
comment on column public.daily_question_templates.active is 'Retire a template by setting false; never delete one already used (FK is ON DELETE RESTRICT).';
alter table only public.daily_question_templates add constraint daily_question_templates_pkey PRIMARY KEY (id);
alter table only public.daily_question_templates add constraint daily_question_templates_question_key UNIQUE (question);
alter table only public.daily_question_templates add constraint daily_question_templates_slot_sequence_key UNIQUE (weekday_slot, sequence);

create table public.daily_questions (
  id uuid not null,
  question_date date not null,
  question text not null,
  category text not null,
  created_at timestamp with time zone not null,
  template_id text
);
comment on column public.daily_questions.template_id is 'M9E provenance: template this day was materialized from. NULL for rows seeded before M9E.';
alter table only public.daily_questions add constraint daily_questions_pkey PRIMARY KEY (id);
alter table only public.daily_questions add constraint daily_questions_question_date_key UNIQUE (question_date);

create table public.device_push_tokens (
  id uuid not null,
  user_id uuid not null,
  couple_id uuid not null,
  token text not null,
  platform text not null,
  created_at timestamp with time zone not null,
  last_seen_at timestamp with time zone not null
);
alter table only public.device_push_tokens add constraint device_push_tokens_pkey PRIMARY KEY (id);
alter table only public.device_push_tokens add constraint device_push_tokens_token_key UNIQUE (token);

create table public.game_session_answers (
  item_id uuid not null,
  actor_role text not null,
  answer_text text,
  answer_index smallint,
  updated_at timestamp with time zone not null
);
alter table only public.game_session_answers add constraint game_session_answers_pkey PRIMARY KEY (item_id, actor_role);

create table public.game_session_items (
  id uuid not null,
  session_id uuid not null,
  position smallint not null,
  source_question_id uuid,
  source_version integer,
  question_text text not null,
  answer_kind text not null,
  options jsonb not null,
  mechanic text not null,
  subject_role text,
  predict_text text,
  family text,
  source_type text,
  source_ref text,
  recipe_id text,
  recipe_version integer,
  topic text,
  perspective text,
  depth smallint,
  fingerprint text,
  context jsonb not null
);
alter table only public.game_session_items add constraint game_session_items_pkey PRIMARY KEY (id);
alter table only public.game_session_items add constraint game_session_items_session_id_position_key UNIQUE (session_id, "position");

create table public.game_session_sides (
  session_id uuid not null,
  actor_role text not null,
  completed_at timestamp with time zone,
  reveal_seen_at timestamp with time zone
);
alter table only public.game_session_sides add constraint game_session_sides_pkey PRIMARY KEY (session_id, actor_role);

create table public.game_sessions (
  id uuid not null,
  couple_id uuid not null,
  game_family text not null,
  content_source text not null,
  started_by_role text not null,
  create_request_id uuid not null,
  started_at timestamp with time zone not null,
  completed_at timestamp with time zone,
  engine_version smallint not null,
  subject_heavy_role text
);
alter table only public.game_sessions add constraint game_sessions_pkey PRIMARY KEY (id);
alter table only public.game_sessions add constraint game_sessions_couple_id_started_by_role_create_request_id_key UNIQUE (couple_id, started_by_role, create_request_id);

create table public.game_v2_catalog (
  id text not null,
  version integer not null,
  family text not null,
  source_type text not null,
  mechanic text not null,
  answer_kind text not null,
  question_text text not null,
  predict_text text,
  options jsonb not null,
  depth smallint not null,
  topic text not null,
  cooldown_class text not null,
  longitudinal boolean not null,
  active boolean not null,
  created_at timestamp with time zone not null
);
comment on table public.game_v2_catalog is 'M11B curated Game V2 prompts. Source of truth: supabase/game-v2/catalog/*.json (generated seed). Retire a prompt with active=false; bump version for a new wording in a new migration. Server-only.';
alter table only public.game_v2_catalog add constraint game_v2_catalog_pkey PRIMARY KEY (id);

create table public.game_v2_cooldowns (
  cooldown_class text not null,
  item_days integer not null,
  recipe_days integer not null,
  source_days integer not null,
  topic_days integer not null,
  note text not null
);
alter table only public.game_v2_cooldowns add constraint game_v2_cooldowns_pkey PRIMARY KEY (cooldown_class);

create table public.game_v2_recipes (
  id text not null,
  version integer not null,
  adapter text not null,
  family text,
  mechanic text not null,
  answer_kind text not null,
  question_text text not null,
  options jsonb not null,
  depth smallint not null,
  topic text not null,
  cooldown_class text not null,
  kind_label text not null,
  active boolean not null,
  created_at timestamp with time zone not null
);
comment on table public.game_v2_recipes is 'M11C curated Game V2 context recipes. Source of truth: supabase/game-v2/recipes/<adapter>.json (generated seed). Server-only.';
alter table only public.game_v2_recipes add constraint game_v2_recipes_pkey PRIMARY KEY (id);

create table public.left_for_you (
  id uuid not null,
  couple_id uuid not null,
  sender_id uuid not null,
  recipient_id uuid not null,
  kind text not null,
  body text,
  media_path text,
  created_at timestamp with time zone not null,
  seen_at timestamp with time zone,
  cleanup_eligible_at timestamp with time zone
);
alter table only public.left_for_you add constraint left_for_you_pkey PRIMARY KEY (id);

create table public.living_provenance (
  id uuid not null,
  couple_id uuid not null,
  source_kind text not null,
  source_ref uuid not null,
  source_key text generated always as (((source_kind || ':'::text) || (source_ref)::text)) stored,
  source_event_completion_id uuid,
  source_bucket_item_id uuid,
  source_title text,
  source_date date,
  target_kind text not null,
  target_ref uuid not null,
  target_moment_id uuid,
  linked_by_role text not null,
  created_at timestamp with time zone not null
);
comment on table public.living_provenance is 'M12B.3: explicit Living Loop derivations (lived source -> Moment). Written only by link_moment_to_source; readable by the same couple; immutable.';
alter table only public.living_provenance add constraint living_provenance_pkey PRIMARY KEY (id);
alter table only public.living_provenance add constraint living_provenance_one_source_per_target UNIQUE (target_kind, target_ref);
alter table only public.living_provenance add constraint living_provenance_one_target_per_source UNIQUE (source_kind, source_ref, target_kind);

create table public.moment_photos (
  id uuid not null,
  moment_id uuid not null,
  couple_id uuid not null,
  created_by uuid not null,
  storage_path text not null,
  caption text,
  position smallint not null,
  created_at timestamp with time zone not null
);
alter table only public.moment_photos add constraint moment_photos_pkey PRIMARY KEY (id);
alter table only public.moment_photos add constraint moment_photos_storage_path_key UNIQUE (storage_path);

create table public.moments (
  id uuid not null,
  couple_id uuid not null,
  created_by uuid not null,
  storage_path text not null,
  caption text,
  moment_date date not null,
  created_at timestamp with time zone not null
);
alter table only public.moments add constraint moments_pkey PRIMARY KEY (id);
alter table only public.moments add constraint moments_storage_path_key UNIQUE (storage_path);

create table public.moods (
  id uuid not null,
  couple_id uuid not null,
  user_id uuid not null,
  mood text not null,
  note text,
  mood_date date not null,
  created_at timestamp with time zone not null
);
alter table only public.moods add constraint moods_pkey PRIMARY KEY (id);
alter table only public.moods add constraint moods_user_id_mood_date_key UNIQUE (user_id, mood_date);

create table public.notification_preferences (
  user_id uuid not null,
  think boolean not null,
  today boolean not null,
  bond boolean not null,
  relationship boolean not null,
  updated_at timestamp with time zone not null,
  left_for_you boolean not null,
  games boolean not null
);
alter table only public.notification_preferences add constraint notification_preferences_pkey PRIMARY KEY (user_id);

create table public.partner_knowledge_attempts (
  id uuid not null,
  couple_id uuid not null,
  user_id uuid not null,
  week_start date not null,
  deck smallint not null,
  guesses jsonb not null,
  score smallint not null,
  xp_awarded integer not null,
  completed_at timestamp with time zone not null
);
alter table only public.partner_knowledge_attempts add constraint partner_knowledge_attempts_pkey PRIMARY KEY (id);
alter table only public.partner_knowledge_attempts add constraint partner_knowledge_attempts_couple_id_user_id_week_start_dec_key UNIQUE (couple_id, user_id, week_start, deck);

create table public.profiles (
  id uuid not null,
  display_name text not null,
  couple_id uuid,
  role text not null,
  created_at timestamp with time zone not null,
  avatar_path text
);
alter table only public.profiles add constraint profiles_pkey PRIMARY KEY (id);

create table public.progression_events (
  id uuid not null,
  couple_id uuid not null,
  actor_id uuid,
  source_kind text not null,
  source_key text not null,
  xp_awarded integer not null,
  counts_rhythm boolean not null,
  action_day date not null,
  created_at timestamp with time zone not null
);
alter table only public.progression_events add constraint progression_events_pkey PRIMARY KEY (id);
alter table only public.progression_events add constraint progression_events_couple_id_source_kind_source_key_key UNIQUE (couple_id, source_kind, source_key);

create table public.progression_reward_catalog (
  id text not null,
  level_required smallint not null,
  category text not null,
  title text not null,
  description text not null,
  token text not null,
  sort_order smallint not null,
  active boolean not null,
  announce boolean not null
);
alter table only public.progression_reward_catalog add constraint progression_reward_catalog_pkey PRIMARY KEY (id);
alter table only public.progression_reward_catalog add constraint progression_reward_catalog_token_key UNIQUE (token);

create table public.progression_reward_views (
  couple_id uuid not null,
  reward_id text not null,
  profile_id uuid not null,
  seen_at timestamp with time zone not null
);
alter table only public.progression_reward_views add constraint progression_reward_views_pkey PRIMARY KEY (couple_id, reward_id, profile_id);

create table public.push_event_log (
  dedupe_key text not null,
  couple_id uuid not null,
  sender_id uuid,
  event_type text not null,
  created_at timestamp with time zone not null
);
alter table only public.push_event_log add constraint push_event_log_pkey PRIMARY KEY (dedupe_key);

create table public.push_subscriptions (
  id uuid not null,
  user_id uuid not null,
  couple_id uuid not null,
  endpoint text not null,
  p256dh text not null,
  auth_key text not null,
  expiration_time bigint,
  user_agent text,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null
);
alter table only public.push_subscriptions add constraint push_subscriptions_pkey PRIMARY KEY (id);
alter table only public.push_subscriptions add constraint push_subscriptions_endpoint_key UNIQUE (endpoint);

create table public.quiz_questions (
  id uuid not null,
  set_id uuid not null,
  position smallint not null,
  question text not null,
  options jsonb not null
);
alter table only public.quiz_questions add constraint quiz_questions_pkey PRIMARY KEY (id);
alter table only public.quiz_questions add constraint quiz_questions_set_id_position_key UNIQUE (set_id, "position");

create table public.quiz_responses (
  id uuid not null,
  set_id uuid not null,
  question_id uuid not null,
  user_id uuid not null,
  couple_id uuid not null,
  answer_index smallint not null,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  week_start date not null
);
alter table only public.quiz_responses add constraint quiz_responses_pkey PRIMARY KEY (id);

create table public.quiz_sets (
  id uuid not null,
  slug text not null,
  title text not null,
  category text not null,
  created_at timestamp with time zone not null,
  mode text not null
);
alter table only public.quiz_sets add constraint quiz_sets_pkey PRIMARY KEY (id);
alter table only public.quiz_sets add constraint quiz_sets_slug_key UNIQUE (slug);

create table public.relationship_milestones (
  id uuid not null,
  couple_id uuid not null,
  milestone_date date not null,
  kind text not null,
  months_together integer not null,
  xp_awarded integer not null,
  awarded_at timestamp with time zone not null
);
alter table only public.relationship_milestones add constraint relationship_milestones_pkey PRIMARY KEY (id);
alter table only public.relationship_milestones add constraint relationship_milestones_couple_id_milestone_date_kind_key UNIQUE (couple_id, milestone_date, kind);

create table public.shared_event_completions (
  id uuid not null,
  event_id uuid not null,
  couple_id uuid not null,
  occurrence_date date not null,
  completed_by uuid not null,
  xp_awarded integer not null,
  completed_at timestamp with time zone not null,
  event_title_snapshot text
);
comment on column public.shared_event_completions.event_title_snapshot is 'M12B.3: shared_events.title when this occurrence was completed. Server-written on insert, immutable. NULL for completions older than M12B.3 (unknown, never guessed).';
alter table only public.shared_event_completions add constraint shared_event_completions_pkey PRIMARY KEY (id);
alter table only public.shared_event_completions add constraint shared_event_completions_event_id_occurrence_date_key UNIQUE (event_id, occurrence_date);

create table public.shared_events (
  id uuid not null,
  couple_id uuid not null,
  created_by uuid not null,
  title text not null,
  event_date date not null,
  event_time time without time zone,
  location text,
  note text,
  recurs_yearly boolean not null,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null
);
alter table only public.shared_events add constraint shared_events_pkey PRIMARY KEY (id);

create table public.shared_messages (
  id uuid not null,
  couple_id uuid not null,
  sender_id uuid not null,
  recipient_id uuid not null,
  kind text not null,
  title text,
  body text not null,
  unlock_at timestamp with time zone,
  opened_at timestamp with time zone,
  created_at timestamp with time zone not null,
  think_operation_id uuid
);
alter table only public.shared_messages add constraint shared_messages_pkey PRIMARY KEY (id);

create table public.stories (
  id uuid not null,
  couple_id uuid not null,
  author_id uuid not null,
  media_path text not null,
  caption text,
  duration_seconds smallint not null,
  created_at timestamp with time zone not null,
  expires_at timestamp with time zone not null
);
alter table only public.stories add constraint stories_pkey PRIMARY KEY (id);

create table public.story_views (
  story_id uuid not null,
  viewer_id uuid not null,
  viewed_at timestamp with time zone not null
);
alter table only public.story_views add constraint story_views_pkey PRIMARY KEY (story_id, viewer_id);

create table public.think_reactions (
  id uuid not null,
  message_id uuid not null,
  reaction text not null,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null
);
comment on table public.think_reactions is 'M4-only one-tap reactions to think messages; recipient-owned and intentionally not a generic reaction system.';
alter table only public.think_reactions add constraint think_reactions_pkey PRIMARY KEY (id);
alter table only public.think_reactions add constraint think_reactions_message_id_key UNIQUE (message_id);

create table public.weekly_quiz_rewards (
  couple_id uuid not null,
  set_id uuid not null,
  week_start date not null,
  score smallint not null,
  xp_awarded integer not null,
  awarded_at timestamp with time zone not null
);
alter table only public.weekly_quiz_rewards add constraint weekly_quiz_rewards_pkey PRIMARY KEY (couple_id, set_id, week_start);

create table public.widget_action_receipts (
  id uuid not null,
  token_id uuid not null,
  action_id uuid not null,
  action_type text not null,
  message_id uuid,
  status text not null,
  created_at timestamp with time zone not null,
  completed_at timestamp with time zone
);
alter table only public.widget_action_receipts add constraint widget_action_receipts_pkey PRIMARY KEY (id);
alter table only public.widget_action_receipts add constraint widget_action_receipts_token_id_action_id_key UNIQUE (token_id, action_id);

create table public.widget_action_tokens (
  id uuid not null,
  couple_id uuid not null,
  profile_id uuid not null,
  device_id_hash text not null,
  token_hash text not null,
  scope text not null,
  created_at timestamp with time zone not null,
  last_used_at timestamp with time zone,
  last_action_at timestamp with time zone,
  expires_at timestamp with time zone not null,
  revoked_at timestamp with time zone
);
alter table only public.widget_action_tokens add constraint widget_action_tokens_pkey PRIMARY KEY (id);
alter table only public.widget_action_tokens add constraint widget_action_tokens_token_hash_key UNIQUE (token_hash);

create table public.widget_scriptable_installations (
  id uuid not null,
  couple_id uuid not null,
  profile_id uuid not null,
  device_id_hash text not null,
  state_token_hash text not null,
  action_token_id uuid not null,
  created_at timestamp with time zone not null,
  expires_at timestamp with time zone not null,
  revoked_at timestamp with time zone
);
alter table only public.widget_scriptable_installations add constraint widget_scriptable_installations_pkey PRIMARY KEY (id);
alter table only public.widget_scriptable_installations add constraint widget_scriptable_installations_action_token_id_key UNIQUE (action_token_id);
alter table only public.widget_scriptable_installations add constraint widget_scriptable_installations_state_token_hash_key UNIQUE (state_token_hash);

create table public.widget_scriptable_setup_codes (
  id uuid not null,
  couple_id uuid not null,
  profile_id uuid not null,
  token_hash text not null,
  created_at timestamp with time zone not null,
  expires_at timestamp with time zone not null,
  consumed_at timestamp with time zone,
  revoked_at timestamp with time zone
);
alter table only public.widget_scriptable_setup_codes add constraint widget_scriptable_setup_codes_pkey PRIMARY KEY (id);
alter table only public.widget_scriptable_setup_codes add constraint widget_scriptable_setup_codes_token_hash_key UNIQUE (token_hash);

create table public.widget_tokens (
  id uuid not null,
  couple_id uuid not null,
  profile_id uuid not null,
  device_label text not null,
  token_hash text not null,
  created_at timestamp with time zone not null,
  last_used_at timestamp with time zone,
  revoked_at timestamp with time zone
);
alter table only public.widget_tokens add constraint widget_tokens_pkey PRIMARY KEY (id);
alter table only public.widget_tokens add constraint widget_tokens_token_hash_key UNIQUE (token_hash);
