-- US backend baseline: constraints
-- GENERATED by scripts/build-supabase-baseline.mjs from the committed
-- production capture (docs/us-2.0/F2A_1_PRODUCTION_CAPTURE*.json).
-- Do not edit by hand: regenerate. Never applied to production by F2A.1.
-- CHECK constraints (some call functions), then FOREIGN KEYs.

set check_function_bodies = off;
select pg_catalog.set_config('search_path', '"\$user", public, extensions', false);

alter table only private.game_swipe_v1_catalog add constraint game_swipe_v1_catalog_id_check CHECK ((id ~ '^swipe-[0-9]{3}$'::text));
alter table only private.game_swipe_v1_catalog add constraint game_swipe_v1_catalog_options_check CHECK (((jsonb_typeof(options) = 'array'::text) AND (jsonb_array_length(options) = 2) AND (jsonb_typeof((options -> 0)) = 'string'::text) AND (jsonb_typeof((options -> 1)) = 'string'::text) AND (btrim((options ->> 0)) <> ''::text) AND (btrim((options ->> 1)) <> ''::text) AND ((options ->> 0) <> (options ->> 1))));
alter table only private.game_swipe_v1_catalog add constraint game_swipe_v1_catalog_question_text_check CHECK (((char_length(btrim(question_text)) >= 12) AND (char_length(btrim(question_text)) <= 240)));
alter table only private.game_swipe_v1_catalog add constraint game_swipe_v1_catalog_topic_check CHECK ((topic ~ '^[a-z_]+$'::text));
alter table only private.game_swipe_v1_catalog add constraint game_swipe_v1_catalog_version_check CHECK ((version > 0));
alter table only public.bond_quest_templates add constraint bond_quest_templates_mode_check CHECK ((mode = ANY (ARRAY['any'::text, 'near'::text, 'far'::text])));
alter table only public.bond_quest_templates add constraint bond_quest_templates_rarity_check CHECK ((rarity = ANY (ARRAY['common'::text, 'uncommon'::text, 'rare'::text, 'epic'::text])));
alter table only public.bond_quest_templates add constraint bond_quest_templates_xp_check CHECK ((xp = ANY (ARRAY[25, 40, 60, 100])));
alter table only public.bond_weekly_quests add constraint bond_weekly_quests_rarity_check CHECK ((rarity = ANY (ARRAY['common'::text, 'uncommon'::text, 'rare'::text, 'epic'::text])));
alter table only public.bond_weekly_quests add constraint bond_weekly_quests_slot_check CHECK (((slot >= 1) AND (slot <= 3)));
alter table only public.bond_weekly_quests add constraint bond_weekly_quests_xp_check CHECK ((xp > 0));
alter table only public.bond_weekly_state add constraint bond_weekly_state_rerolls_used_check CHECK (((rerolls_used >= 0) AND (rerolls_used <= 3)));
alter table only public.bucket_items add constraint bucket_items_archived_unlived_unlinked_check CHECK (((status <> 'archived'::text) OR (completed_at IS NOT NULL) OR (calendar_entry_id IS NULL)));
alter table only public.bucket_items add constraint bucket_items_link_url_check CHECK (((link_url IS NULL) OR (link_url ~* '^https?://'::text)));
alter table only public.bucket_items add constraint bucket_items_lived_proposal_pair_check CHECK (((lived_proposed_by IS NULL) = (lived_proposed_at IS NULL)));
alter table only public.bucket_items add constraint bucket_items_status_calendar_link_check CHECK ((((status = 'idea'::text) AND (calendar_entry_id IS NULL)) OR ((status = 'scheduled'::text) AND (calendar_entry_id IS NOT NULL)) OR (status = 'lived'::text) OR (status = 'archived'::text)));
alter table only public.bucket_items add constraint bucket_items_status_check CHECK ((status = ANY (ARRAY['idea'::text, 'scheduled'::text, 'lived'::text, 'archived'::text])));
alter table only public.calendar_entries add constraint calendar_entries_all_day_range_check CHECK (((is_all_day = false) OR (end_date >= start_date)));
alter table only public.calendar_entries add constraint calendar_entries_entry_type_check CHECK ((entry_type = ANY (ARRAY['personal'::text, 'shared'::text])));
alter table only public.calendar_entries add constraint calendar_entries_owner_by_type_check CHECK ((((entry_type = 'personal'::text) AND (owner_id IS NOT NULL)) OR ((entry_type = 'shared'::text) AND (owner_id IS NULL))));
alter table only public.calendar_entries add constraint calendar_entries_personal_owner_is_creator_check CHECK (((entry_type <> 'personal'::text) OR (owner_id = created_by)));
alter table only public.calendar_entries add constraint calendar_entries_temporal_representation_check CHECK ((((is_all_day = false) AND (starts_at IS NOT NULL) AND (ends_at IS NOT NULL) AND (start_date IS NULL) AND (end_date IS NULL)) OR ((is_all_day = true) AND (start_date IS NOT NULL) AND (end_date IS NOT NULL) AND (starts_at IS NULL) AND (ends_at IS NULL))));
alter table only public.calendar_entries add constraint calendar_entries_timed_range_check CHECK (((is_all_day = true) OR (ends_at > starts_at)));
alter table only public.calendar_entries add constraint calendar_entries_title_check CHECK (((char_length(btrim(title)) >= 1) AND (char_length(btrim(title)) <= 200)));
alter table only public.calendar_entries add constraint calendar_entries_visibility_check CHECK ((visibility = 'full'::text));
alter table only public.calendar_reminders add constraint calendar_reminders_allday_offset_check CHECK (calendar_reminder_offset_valid(entry_id, offset_minutes));
alter table only public.calendar_reminders add constraint calendar_reminders_offset_check CHECK ((offset_minutes = ANY (ARRAY[10, 30, 60, 1440])));
alter table only public.calendar_reminders add constraint calendar_reminders_recipient_in_couple_check CHECK (calendar_reminder_recipient_in_couple(couple_id, recipient_id));
alter table only public.couple_invites add constraint couple_invites_role_check CHECK ((role = ANY (ARRAY['francesco'::text, 'beatrice'::text])));
alter table only public.couple_locations add constraint couple_locations_latitude_check CHECK (((latitude >= ('-90'::integer)::double precision) AND (latitude <= (90)::double precision)));
alter table only public.couple_locations add constraint couple_locations_longitude_check CHECK (((longitude >= ('-180'::integer)::double precision) AND (longitude <= (180)::double precision)));
alter table only public.couple_questions add constraint couple_questions_answer_kind_check CHECK ((answer_kind = ANY (ARRAY['open'::text, 'choice'::text])));
alter table only public.couple_questions add constraint couple_questions_author_role_check CHECK ((author_role = ANY (ARRAY['francesco'::text, 'beatrice'::text])));
alter table only public.couple_questions add constraint couple_questions_check CHECK (
CASE
    WHEN (jsonb_typeof(options) = 'array'::text) THEN (((answer_kind = 'open'::text) AND (jsonb_array_length(options) = 0)) OR ((answer_kind = 'choice'::text) AND ((jsonb_array_length(options) >= 2) AND (jsonb_array_length(options) <= 4))))
    ELSE false
END);
alter table only public.couple_questions add constraint couple_questions_families_check CHECK ((((cardinality(families) >= 1) AND (cardinality(families) <= 6)) AND (families <@ private.game_v2_families()) AND (('quanto_mi_conosci'::text <> ALL (families)) OR (answer_kind = 'choice'::text))));
alter table only public.couple_questions add constraint couple_questions_origin_check CHECK ((origin = ANY (ARRAY['library'::text, 'weekly'::text])));
alter table only public.couple_questions add constraint couple_questions_question_text_check CHECK (((char_length(btrim(question_text)) >= 1) AND (char_length(btrim(question_text)) <= 300)));
alter table only public.couple_questions add constraint couple_questions_version_check CHECK ((version > 0));
alter table only public.couple_questions add constraint couple_questions_weekly_shape_check CHECK ((((origin = 'library'::text) AND (week_start IS NULL)) OR ((origin = 'weekly'::text) AND (week_start IS NOT NULL) AND (EXTRACT(isodow FROM week_start) = (1)::numeric) AND (author_role = private.game_v2_weekly_role(week_start)))));
alter table only public.couples add constraint couples_bond_xp_check CHECK ((bond_xp >= 0));
alter table only public.daily_question_keepsakes add constraint daily_question_keepsakes_kept_by_role_check CHECK ((kept_by_role = ANY (ARRAY['francesco'::text, 'beatrice'::text])));
alter table only public.daily_question_keepsakes add constraint daily_question_keepsakes_question_text_check CHECK (((char_length(btrim(question_text)) >= 1) AND (char_length(btrim(question_text)) <= 500)));
alter table only public.daily_question_keepsakes add constraint daily_question_keepsakes_source_kind_check CHECK ((source_kind = 'daily_question'::text));
alter table only public.daily_question_outcomes add constraint daily_question_outcomes_author_role_check CHECK ((author_role = ANY (ARRAY['francesco'::text, 'beatrice'::text])));
alter table only public.daily_question_outcomes add constraint daily_question_outcomes_body_check CHECK (((char_length(btrim(body)) >= 1) AND (char_length(btrim(body)) <= 1000)));
alter table only public.daily_question_outcomes add constraint daily_question_outcomes_revision_check CHECK ((revision > 0));
alter table only public.daily_question_reveal_states add constraint daily_question_reveal_states_actor_role_check CHECK ((actor_role = ANY (ARRAY['francesco'::text, 'beatrice'::text])));
alter table only public.daily_question_reveal_states add constraint daily_question_reveal_states_reaction_check CHECK (((reaction IS NULL) OR (reaction = ANY (ARRAY['heart'::text, 'angry'::text, 'cry'::text]))));
alter table only public.daily_question_templates add constraint daily_question_templates_id_theme CHECK (((id ~ '^[a-z_]+-[0-9]{2,}$'::text) AND (split_part(id, '-'::text, 1) = theme)));
alter table only public.daily_question_templates add constraint daily_question_templates_question_check CHECK (((char_length(btrim(question)) >= 8) AND (char_length(btrim(question)) <= 240)));
alter table only public.daily_question_templates add constraint daily_question_templates_sequence_check CHECK ((sequence >= 1));
alter table only public.daily_question_templates add constraint daily_question_templates_theme_check CHECK ((theme = ANY (ARRAY['noi_adesso'::text, 'scoprirsi'::text, 'ricordi'::text, 'desideri'::text, 'vicinanza'::text, 'gioco'::text, 'profonda'::text])));
alter table only public.daily_question_templates add constraint daily_question_templates_theme_weekday CHECK ((weekday_slot =
CASE theme
    WHEN 'noi_adesso'::text THEN 1
    WHEN 'scoprirsi'::text THEN 2
    WHEN 'ricordi'::text THEN 3
    WHEN 'desideri'::text THEN 4
    WHEN 'vicinanza'::text THEN 5
    WHEN 'gioco'::text THEN 6
    WHEN 'profonda'::text THEN 7
    ELSE NULL::integer
END));
alter table only public.daily_question_templates add constraint daily_question_templates_weekday_slot_check CHECK (((weekday_slot >= 1) AND (weekday_slot <= 7)));
alter table only public.device_push_tokens add constraint device_push_tokens_platform_check CHECK ((platform = ANY (ARRAY['android'::text, 'ios'::text])));
alter table only public.game_session_answers add constraint game_session_answers_actor_role_check CHECK ((actor_role = ANY (ARRAY['francesco'::text, 'beatrice'::text])));
alter table only public.game_session_answers add constraint game_session_answers_check CHECK ((((answer_text IS NOT NULL) AND (answer_index IS NULL) AND ((char_length(btrim(answer_text)) >= 1) AND (char_length(btrim(answer_text)) <= 1000))) OR ((answer_text IS NULL) AND (answer_index IS NOT NULL) AND (answer_index >= 0))));
alter table only public.game_session_items add constraint game_session_items_answer_kind_check CHECK ((answer_kind = ANY (ARRAY['open'::text, 'choice'::text])));
alter table only public.game_session_items add constraint game_session_items_check CHECK (
CASE
    WHEN (jsonb_typeof(options) = 'array'::text) THEN (((answer_kind = 'open'::text) AND (jsonb_array_length(options) = 0)) OR ((answer_kind = 'choice'::text) AND ((jsonb_array_length(options) >= 2) AND (jsonb_array_length(options) <= 4))))
    ELSE false
END);
alter table only public.game_session_items add constraint game_session_items_context_check CHECK ((jsonb_typeof(context) = 'object'::text));
alter table only public.game_session_items add constraint game_session_items_family_check CHECK (((family IS NULL) OR (family = ANY (private.game_v2_families()))));
alter table only public.game_session_items add constraint game_session_items_mechanic_check CHECK ((((mechanic = 'reciprocal'::text) AND (subject_role IS NULL) AND (predict_text IS NULL)) OR ((mechanic = 'prediction'::text) AND (answer_kind = 'choice'::text) AND (subject_role = ANY (ARRAY['francesco'::text, 'beatrice'::text])) AND ((char_length(btrim(predict_text)) >= 1) AND (char_length(btrim(predict_text)) <= 300)))));
alter table only public.game_session_items add constraint game_session_items_position_check CHECK ((("position" >= 1) AND ("position" <= 20)));
alter table only public.game_session_items add constraint game_session_items_question_text_check CHECK (((char_length(btrim(question_text)) >= 1) AND (char_length(btrim(question_text)) <= 300)));
alter table only public.game_session_items add constraint game_session_items_source_version_check CHECK (((source_version IS NULL) OR (source_version > 0)));
alter table only public.game_session_sides add constraint game_session_sides_actor_role_check CHECK ((actor_role = ANY (ARRAY['francesco'::text, 'beatrice'::text])));
alter table only public.game_sessions add constraint game_sessions_content_source_check CHECK ((content_source = ANY (ARRAY['curated'::text, 'partner_knowledge'::text, 'couple_custom'::text, 'us_context'::text, 'mixed'::text])));
alter table only public.game_sessions add constraint game_sessions_engine_version_check CHECK ((engine_version = ANY (ARRAY[1, 2])));
alter table only public.game_sessions add constraint game_sessions_game_family_check CHECK (((char_length(game_family) >= 1) AND (char_length(game_family) <= 48)));
alter table only public.game_sessions add constraint game_sessions_started_by_role_check CHECK ((started_by_role = ANY (ARRAY['francesco'::text, 'beatrice'::text])));
alter table only public.game_sessions add constraint game_sessions_subject_heavy_role_check CHECK (((subject_heavy_role IS NULL) OR (subject_heavy_role = ANY (ARRAY['francesco'::text, 'beatrice'::text]))));
alter table only public.game_sessions add constraint game_sessions_v2_family_check CHECK (((engine_version = 1) OR (game_family = ANY (ARRAY['per_voi'::text, 'swipe'::text])) OR (game_family = ANY (private.game_v2_families()))));
alter table only public.game_v2_catalog add constraint game_v2_catalog_answer_kind_check CHECK ((answer_kind = ANY (ARRAY['open'::text, 'choice'::text])));
alter table only public.game_v2_catalog add constraint game_v2_catalog_check CHECK ((split_part(id, '-'::text, 1) = family));
alter table only public.game_v2_catalog add constraint game_v2_catalog_check1 CHECK (
CASE
    WHEN (jsonb_typeof(options) = 'array'::text) THEN (((answer_kind = 'open'::text) AND (jsonb_array_length(options) = 0)) OR ((answer_kind = 'choice'::text) AND ((jsonb_array_length(options) >= 2) AND (jsonb_array_length(options) <= 4))))
    ELSE false
END);
alter table only public.game_v2_catalog add constraint game_v2_catalog_check2 CHECK ((((mechanic = 'reciprocal'::text) AND (predict_text IS NULL)) OR ((mechanic = 'prediction'::text) AND (answer_kind = 'choice'::text) AND (family = 'quanto_mi_conosci'::text) AND (predict_text ~~ '%{subject}%'::text))));
alter table only public.game_v2_catalog add constraint game_v2_catalog_check3 CHECK (((mechanic = 'prediction'::text) OR (family <> 'quanto_mi_conosci'::text)));
alter table only public.game_v2_catalog add constraint game_v2_catalog_depth_check CHECK (((depth >= 1) AND (depth <= 3)));
alter table only public.game_v2_catalog add constraint game_v2_catalog_family_check CHECK ((family = ANY (private.game_v2_families())));
alter table only public.game_v2_catalog add constraint game_v2_catalog_id_check CHECK ((id ~ '^[a-z_]+-[0-9]{3}$'::text));
alter table only public.game_v2_catalog add constraint game_v2_catalog_mechanic_check CHECK ((mechanic = ANY (ARRAY['reciprocal'::text, 'prediction'::text])));
alter table only public.game_v2_catalog add constraint game_v2_catalog_predict_text_check CHECK (((predict_text IS NULL) OR ((char_length(btrim(predict_text)) >= 12) AND (char_length(btrim(predict_text)) <= 240))));
alter table only public.game_v2_catalog add constraint game_v2_catalog_question_text_check CHECK (((char_length(btrim(question_text)) >= 12) AND (char_length(btrim(question_text)) <= 240)));
alter table only public.game_v2_catalog add constraint game_v2_catalog_source_type_check CHECK ((source_type = 'curated'::text));
alter table only public.game_v2_catalog add constraint game_v2_catalog_topic_check CHECK ((topic ~ '^[a-z_]+$'::text));
alter table only public.game_v2_catalog add constraint game_v2_catalog_version_check CHECK ((version > 0));
alter table only public.game_v2_cooldowns add constraint game_v2_cooldowns_cooldown_class_check CHECK ((cooldown_class ~ '^[a-z_]+$'::text));
alter table only public.game_v2_cooldowns add constraint game_v2_cooldowns_item_days_check CHECK ((item_days >= 0));
alter table only public.game_v2_cooldowns add constraint game_v2_cooldowns_recipe_days_check CHECK ((recipe_days >= 0));
alter table only public.game_v2_cooldowns add constraint game_v2_cooldowns_source_days_check CHECK ((source_days >= 0));
alter table only public.game_v2_cooldowns add constraint game_v2_cooldowns_topic_days_check CHECK ((topic_days >= 0));
alter table only public.game_v2_recipes add constraint game_v2_recipes_adapter_check CHECK ((adapter = ANY (ARRAY['da_vivere_idea'::text, 'da_vivere_lived'::text, 'calendar_upcoming'::text, 'calendar_past'::text, 'moment'::text, 'conservati'::text, 'longitudinal'::text])));
alter table only public.game_v2_recipes add constraint game_v2_recipes_answer_kind_check CHECK ((answer_kind = ANY (ARRAY['open'::text, 'choice'::text])));
alter table only public.game_v2_recipes add constraint game_v2_recipes_check CHECK ((split_part(id, '-'::text, 1) = adapter));
alter table only public.game_v2_recipes add constraint game_v2_recipes_check1 CHECK (((adapter = 'longitudinal'::text) = (family IS NULL)));
alter table only public.game_v2_recipes add constraint game_v2_recipes_check2 CHECK (((adapter <> 'longitudinal'::text) OR ((question_text = '{previous_question}'::text) AND (answer_kind = 'open'::text) AND (cooldown_class = 'longitudinal'::text))));
alter table only public.game_v2_recipes add constraint game_v2_recipes_check3 CHECK (((adapter = 'longitudinal'::text) OR (cooldown_class = 'context'::text)));
alter table only public.game_v2_recipes add constraint game_v2_recipes_check4 CHECK (((adapter <> ALL (ARRAY['da_vivere_idea'::text, 'da_vivere_lived'::text, 'calendar_upcoming'::text, 'calendar_past'::text, 'moment'::text])) OR (question_text ~~ '%{title}%'::text)));
alter table only public.game_v2_recipes add constraint game_v2_recipes_check5 CHECK (
CASE
    WHEN (jsonb_typeof(options) = 'array'::text) THEN (((answer_kind = 'open'::text) AND (jsonb_array_length(options) = 0)) OR ((answer_kind = 'choice'::text) AND ((jsonb_array_length(options) >= 2) AND (jsonb_array_length(options) <= 4))))
    ELSE false
END);
alter table only public.game_v2_recipes add constraint game_v2_recipes_depth_check CHECK (((depth >= 1) AND (depth <= 3)));
alter table only public.game_v2_recipes add constraint game_v2_recipes_family_check CHECK (((family IS NULL) OR (family = ANY (private.game_v2_families()))));
alter table only public.game_v2_recipes add constraint game_v2_recipes_id_check CHECK ((id ~ '^[a-z_]+-[0-9]{3}$'::text));
alter table only public.game_v2_recipes add constraint game_v2_recipes_kind_label_check CHECK (((char_length(btrim(kind_label)) >= 3) AND (char_length(btrim(kind_label)) <= 40)));
alter table only public.game_v2_recipes add constraint game_v2_recipes_mechanic_check CHECK ((mechanic = 'reciprocal'::text));
alter table only public.game_v2_recipes add constraint game_v2_recipes_question_text_check CHECK ((((char_length(btrim(question_text)) >= 12) AND (char_length(btrim(question_text)) <= 240)) OR (question_text = '{previous_question}'::text)));
alter table only public.game_v2_recipes add constraint game_v2_recipes_topic_check CHECK ((topic ~ '^ctx_[a-z_]+$'::text));
alter table only public.game_v2_recipes add constraint game_v2_recipes_version_check CHECK ((version > 0));
alter table only public.left_for_you add constraint left_for_you_av_contract_check CHECK (((kind <> ALL (ARRAY['audio'::text, 'video'::text])) OR ((media_path IS NOT NULL) AND (char_length(media_path) <= 512) AND ((body IS NULL) OR (char_length(body) <= 280)))));
alter table only public.left_for_you add constraint left_for_you_kind_m5c_check CHECK ((kind = ANY (ARRAY['text'::text, 'photo'::text, 'audio'::text, 'video'::text, 'music'::text])));
alter table only public.left_for_you add constraint left_for_you_music_contract_check CHECK (((kind <> 'music'::text) OR ((media_path IS NOT NULL) AND ("left"(media_path, 8) = 'https://'::text) AND (char_length(media_path) <= 512) AND (POSITION((' '::text) IN (media_path)) = 0) AND ((body IS NULL) OR (char_length(body) <= 280)))));
alter table only public.left_for_you add constraint left_for_you_no_self_check CHECK ((sender_id <> recipient_id));
alter table only public.left_for_you add constraint left_for_you_photo_contract_check CHECK (((kind <> 'photo'::text) OR ((media_path IS NOT NULL) AND (char_length(media_path) <= 512) AND ((body IS NULL) OR (char_length(body) <= 280)))));
alter table only public.left_for_you add constraint left_for_you_text_contract_check CHECK (((kind <> 'text'::text) OR ((body IS NOT NULL) AND ((char_length(btrim(body)) >= 1) AND (char_length(btrim(body)) <= 1000)) AND (media_path IS NULL))));
alter table only public.living_provenance add constraint living_provenance_linked_by_role_check CHECK ((linked_by_role = ANY (ARRAY['francesco'::text, 'beatrice'::text])));
alter table only public.living_provenance add constraint living_provenance_source_fk_check CHECK ((((source_kind = 'shared_event_completion'::text) AND (source_bucket_item_id IS NULL) AND ((source_event_completion_id IS NULL) OR (source_event_completion_id = source_ref))) OR ((source_kind = 'da_vivere'::text) AND (source_event_completion_id IS NULL) AND ((source_bucket_item_id IS NULL) OR (source_bucket_item_id = source_ref)))));
alter table only public.living_provenance add constraint living_provenance_source_kind_check CHECK ((source_kind = ANY (ARRAY['shared_event_completion'::text, 'da_vivere'::text])));
alter table only public.living_provenance add constraint living_provenance_source_title_check CHECK (((source_title IS NULL) OR (char_length(source_title) <= 200)));
alter table only public.living_provenance add constraint living_provenance_target_fk_check CHECK (((target_kind = 'moment'::text) AND (target_moment_id = target_ref)));
alter table only public.living_provenance add constraint living_provenance_target_kind_check CHECK ((target_kind = 'moment'::text));
alter table only public.moment_photos add constraint moment_photos_caption_len CHECK (((caption IS NULL) OR (char_length(caption) <= 180)));
alter table only public.moment_photos add constraint moment_photos_position_positive CHECK (("position" >= 1));
alter table only public.partner_knowledge_attempts add constraint partner_knowledge_attempts_deck_check CHECK (((deck >= 1) AND (deck <= 3)));
alter table only public.partner_knowledge_attempts add constraint partner_knowledge_attempts_score_check CHECK (((score >= 0) AND (score <= 5)));
alter table only public.partner_knowledge_attempts add constraint partner_knowledge_attempts_xp_awarded_check CHECK (((xp_awarded >= 0) AND (xp_awarded <= 50)));
alter table only public.profiles add constraint profiles_role_check CHECK ((role = ANY (ARRAY['francesco'::text, 'beatrice'::text])));
alter table only public.progression_events add constraint progression_events_source_key_check CHECK (((length(source_key) >= 1) AND (length(source_key) <= 180)));
alter table only public.progression_events add constraint progression_events_source_kind_check CHECK ((source_kind = ANY (ARRAY['quest'::text, 'event'::text, 'milestone'::text, 'daily'::text, 'game'::text, 'think'::text, 'moment'::text])));
alter table only public.progression_events add constraint progression_events_xp_awarded_check CHECK ((xp_awarded >= 0));
alter table only public.progression_reward_catalog add constraint progression_reward_catalog_category_check CHECK ((category = ANY (ARRAY['frame'::text, 'theme'::text, 'accent'::text, 'effect'::text, 'badge'::text, 'sticker'::text, 'ring'::text])));
alter table only public.progression_reward_catalog add constraint progression_reward_catalog_level_required_check CHECK ((level_required >= 1));
alter table only public.quiz_questions add constraint quiz_questions_options_check CHECK ((jsonb_typeof(options) = 'array'::text));
alter table only public.quiz_questions add constraint quiz_questions_position_check CHECK ((("position" >= 1) AND ("position" <= 10)));
alter table only public.quiz_responses add constraint quiz_responses_answer_index_check CHECK (((answer_index >= 0) AND (answer_index <= 9)));
alter table only public.quiz_sets add constraint quiz_sets_mode_check CHECK ((mode = ANY (ARRAY['match'::text, 'never_have_i'::text, 'agree_disagree'::text, 'would_you_rather'::text])));
alter table only public.relationship_milestones add constraint relationship_milestones_kind_check CHECK ((kind = ANY (ARRAY['monthiversary'::text, 'anniversary'::text])));
alter table only public.relationship_milestones add constraint relationship_milestones_months_together_check CHECK ((months_together > 0));
alter table only public.relationship_milestones add constraint relationship_milestones_xp_awarded_check CHECK (((xp_awarded >= 0) AND (xp_awarded <= 500)));
alter table only public.shared_event_completions add constraint shared_event_completions_xp_awarded_check CHECK (((xp_awarded >= 0) AND (xp_awarded <= 500)));
alter table only public.shared_events add constraint shared_events_location_check CHECK (((location IS NULL) OR (char_length(location) <= 160)));
alter table only public.shared_events add constraint shared_events_note_check CHECK (((note IS NULL) OR (char_length(note) <= 500)));
alter table only public.shared_events add constraint shared_events_title_check CHECK (((char_length(title) >= 1) AND (char_length(title) <= 120)));
alter table only public.shared_messages add constraint shared_messages_kind_check CHECK ((kind = ANY (ARRAY['normal'::text, 'open_when'::text, 'poke'::text, 'scheduled'::text, 'think'::text])));
alter table only public.stories add constraint stories_duration_seconds_check CHECK (((duration_seconds >= 1) AND (duration_seconds <= 10)));
alter table only public.think_reactions add constraint think_reactions_reaction_check CHECK ((reaction = ANY (ARRAY['heart'::text, 'hug'::text, 'miss_you'::text])));
alter table only public.weekly_quiz_rewards add constraint weekly_quiz_rewards_score_check CHECK (((score >= 0) AND (score <= 10)));
alter table only public.weekly_quiz_rewards add constraint weekly_quiz_rewards_xp_awarded_check CHECK (((xp_awarded >= 0) AND (xp_awarded <= 100)));
alter table only public.widget_action_receipts add constraint widget_action_receipts_action_type_check CHECK ((action_type = 'think:send'::text));
alter table only public.widget_action_receipts add constraint widget_action_receipts_status_check CHECK ((status = ANY (ARRAY['processing'::text, 'sent'::text])));
alter table only public.widget_action_tokens add constraint widget_action_tokens_device_id_hash_check CHECK ((device_id_hash ~ '^[a-f0-9]{64}$'::text));
alter table only public.widget_action_tokens add constraint widget_action_tokens_scope_check CHECK ((scope = 'think:send'::text));
alter table only public.widget_action_tokens add constraint widget_action_tokens_token_hash_check CHECK ((token_hash ~ '^[a-f0-9]{64}$'::text));
alter table only public.widget_scriptable_installations add constraint widget_scriptable_installations_device_id_hash_check CHECK ((device_id_hash ~ '^[a-f0-9]{64}$'::text));
alter table only public.widget_scriptable_installations add constraint widget_scriptable_installations_state_token_hash_check CHECK ((state_token_hash ~ '^[a-f0-9]{64}$'::text));
alter table only public.widget_scriptable_setup_codes add constraint widget_scriptable_setup_codes_token_hash_check CHECK ((token_hash ~ '^[a-f0-9]{64}$'::text));
alter table only public.activity add constraint activity_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table only public.activity add constraint activity_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.bond_weekly_quests add constraint bond_weekly_quests_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.bond_weekly_quests add constraint bond_weekly_quests_template_key_fkey FOREIGN KEY (template_key) REFERENCES bond_quest_templates(key);
alter table only public.bond_weekly_state add constraint bond_weekly_state_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.bucket_items add constraint bucket_items_calendar_entry_id_fkey FOREIGN KEY (calendar_entry_id) REFERENCES calendar_entries(id) ON DELETE RESTRICT;
alter table only public.bucket_items add constraint bucket_items_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.bucket_items add constraint bucket_items_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table only public.calendar_entries add constraint calendar_entries_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.calendar_entries add constraint calendar_entries_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE CASCADE;
alter table only public.calendar_entries add constraint calendar_entries_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table only public.calendar_reminders add constraint calendar_reminders_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.calendar_reminders add constraint calendar_reminders_entry_id_fkey FOREIGN KEY (entry_id) REFERENCES calendar_entries(id) ON DELETE CASCADE;
alter table only public.calendar_reminders add constraint calendar_reminders_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table only public.calendar_reminders add constraint calendar_reminders_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES profiles(id) ON DELETE CASCADE;
alter table only public.conserva_contributions add constraint conserva_contributions_conserved_by_fkey FOREIGN KEY (conserved_by) REFERENCES profiles(id) ON DELETE CASCADE;
alter table only public.conserva_contributions add constraint conserva_contributions_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.conserva_contributions add constraint conserva_contributions_source_item_id_fkey FOREIGN KEY (source_item_id) REFERENCES left_for_you(id) ON DELETE CASCADE;
alter table only public.conserva_contributions add constraint conserva_contributions_source_sender_id_fkey FOREIGN KEY (source_sender_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table only public.couple_invites add constraint couple_invites_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.couple_invites add constraint couple_invites_used_by_fkey FOREIGN KEY (used_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table only public.couple_locations add constraint couple_locations_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.couple_locations add constraint couple_locations_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table only public.couple_progression_preferences add constraint couple_progression_preferences_accent_reward_id_fkey FOREIGN KEY (accent_reward_id) REFERENCES progression_reward_catalog(id) ON DELETE SET NULL;
alter table only public.couple_progression_preferences add constraint couple_progression_preferences_badge_reward_id_fkey FOREIGN KEY (badge_reward_id) REFERENCES progression_reward_catalog(id) ON DELETE SET NULL;
alter table only public.couple_progression_preferences add constraint couple_progression_preferences_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.couple_progression_preferences add constraint couple_progression_preferences_effect_reward_id_fkey FOREIGN KEY (effect_reward_id) REFERENCES progression_reward_catalog(id) ON DELETE SET NULL;
alter table only public.couple_progression_preferences add constraint couple_progression_preferences_frame_reward_id_fkey FOREIGN KEY (frame_reward_id) REFERENCES progression_reward_catalog(id) ON DELETE SET NULL;
alter table only public.couple_progression_preferences add constraint couple_progression_preferences_ring_reward_id_fkey FOREIGN KEY (ring_reward_id) REFERENCES progression_reward_catalog(id) ON DELETE SET NULL;
alter table only public.couple_progression_preferences add constraint couple_progression_preferences_sticker_reward_id_fkey FOREIGN KEY (sticker_reward_id) REFERENCES progression_reward_catalog(id) ON DELETE SET NULL;
alter table only public.couple_progression_preferences add constraint couple_progression_preferences_theme_reward_id_fkey FOREIGN KEY (theme_reward_id) REFERENCES progression_reward_catalog(id) ON DELETE SET NULL;
alter table only public.couple_progression_preferences add constraint couple_progression_preferences_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table only public.couple_questions add constraint couple_questions_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.couple_reward_unlocks add constraint couple_reward_unlocks_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.couple_reward_unlocks add constraint couple_reward_unlocks_reward_id_fkey FOREIGN KEY (reward_id) REFERENCES progression_reward_catalog(id) ON DELETE RESTRICT;
alter table only public.daily_answers add constraint daily_answers_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.daily_answers add constraint daily_answers_question_id_fkey FOREIGN KEY (question_id) REFERENCES daily_questions(id) ON DELETE CASCADE;
alter table only public.daily_answers add constraint daily_answers_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table only public.daily_question_keepsakes add constraint daily_question_keepsakes_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.daily_question_keepsakes add constraint daily_question_keepsakes_question_id_fkey FOREIGN KEY (question_id) REFERENCES daily_questions(id) ON DELETE RESTRICT;
alter table only public.daily_question_outcomes add constraint daily_question_outcomes_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.daily_question_outcomes add constraint daily_question_outcomes_question_id_fkey FOREIGN KEY (question_id) REFERENCES daily_questions(id) ON DELETE CASCADE;
alter table only public.daily_question_reveal_states add constraint daily_question_reveal_states_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.daily_question_reveal_states add constraint daily_question_reveal_states_question_id_fkey FOREIGN KEY (question_id) REFERENCES daily_questions(id) ON DELETE CASCADE;
alter table only public.daily_questions add constraint daily_questions_template_id_fkey FOREIGN KEY (template_id) REFERENCES daily_question_templates(id) ON DELETE RESTRICT;
alter table only public.device_push_tokens add constraint device_push_tokens_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.device_push_tokens add constraint device_push_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table only public.game_session_answers add constraint game_session_answers_item_id_fkey FOREIGN KEY (item_id) REFERENCES game_session_items(id) ON DELETE CASCADE;
alter table only public.game_session_items add constraint game_session_items_session_id_fkey FOREIGN KEY (session_id) REFERENCES game_sessions(id) ON DELETE CASCADE;
alter table only public.game_session_items add constraint game_session_items_source_question_id_fkey FOREIGN KEY (source_question_id) REFERENCES couple_questions(id);
alter table only public.game_session_sides add constraint game_session_sides_session_id_fkey FOREIGN KEY (session_id) REFERENCES game_sessions(id) ON DELETE CASCADE;
alter table only public.game_sessions add constraint game_sessions_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.game_v2_catalog add constraint game_v2_catalog_cooldown_class_fkey FOREIGN KEY (cooldown_class) REFERENCES game_v2_cooldowns(cooldown_class);
alter table only public.game_v2_recipes add constraint game_v2_recipes_cooldown_class_fkey FOREIGN KEY (cooldown_class) REFERENCES game_v2_cooldowns(cooldown_class);
alter table only public.left_for_you add constraint left_for_you_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.left_for_you add constraint left_for_you_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table only public.left_for_you add constraint left_for_you_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table only public.living_provenance add constraint living_provenance_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.living_provenance add constraint living_provenance_source_bucket_item_id_fkey FOREIGN KEY (source_bucket_item_id) REFERENCES bucket_items(id) ON DELETE SET NULL;
alter table only public.living_provenance add constraint living_provenance_source_event_completion_id_fkey FOREIGN KEY (source_event_completion_id) REFERENCES shared_event_completions(id) ON DELETE SET NULL;
alter table only public.living_provenance add constraint living_provenance_target_moment_id_fkey FOREIGN KEY (target_moment_id) REFERENCES moments(id) ON DELETE CASCADE;
alter table only public.moment_photos add constraint moment_photos_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.moment_photos add constraint moment_photos_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE CASCADE;
alter table only public.moment_photos add constraint moment_photos_moment_id_fkey FOREIGN KEY (moment_id) REFERENCES moments(id) ON DELETE CASCADE;
alter table only public.moments add constraint moments_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.moments add constraint moments_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE CASCADE;
alter table only public.moods add constraint moods_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.moods add constraint moods_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table only public.notification_preferences add constraint notification_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table only public.partner_knowledge_attempts add constraint partner_knowledge_attempts_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.partner_knowledge_attempts add constraint partner_knowledge_attempts_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table only public.profiles add constraint profiles_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.profiles add constraint profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table only public.progression_events add constraint progression_events_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table only public.progression_events add constraint progression_events_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.progression_reward_views add constraint progression_reward_views_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.progression_reward_views add constraint progression_reward_views_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table only public.progression_reward_views add constraint progression_reward_views_reward_id_fkey FOREIGN KEY (reward_id) REFERENCES progression_reward_catalog(id) ON DELETE RESTRICT;
alter table only public.push_event_log add constraint push_event_log_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.push_event_log add constraint push_event_log_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table only public.push_subscriptions add constraint push_subscriptions_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.push_subscriptions add constraint push_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table only public.quiz_questions add constraint quiz_questions_set_id_fkey FOREIGN KEY (set_id) REFERENCES quiz_sets(id) ON DELETE CASCADE;
alter table only public.quiz_responses add constraint quiz_responses_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.quiz_responses add constraint quiz_responses_question_id_fkey FOREIGN KEY (question_id) REFERENCES quiz_questions(id) ON DELETE CASCADE;
alter table only public.quiz_responses add constraint quiz_responses_set_id_fkey FOREIGN KEY (set_id) REFERENCES quiz_sets(id) ON DELETE CASCADE;
alter table only public.quiz_responses add constraint quiz_responses_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table only public.relationship_milestones add constraint relationship_milestones_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.shared_event_completions add constraint shared_event_completions_completed_by_fkey FOREIGN KEY (completed_by) REFERENCES profiles(id);
alter table only public.shared_event_completions add constraint shared_event_completions_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.shared_event_completions add constraint shared_event_completions_event_id_fkey FOREIGN KEY (event_id) REFERENCES shared_events(id) ON DELETE RESTRICT;
alter table only public.shared_events add constraint shared_events_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.shared_events add constraint shared_events_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE CASCADE;
alter table only public.shared_messages add constraint shared_messages_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.shared_messages add constraint shared_messages_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table only public.shared_messages add constraint shared_messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table only public.stories add constraint stories_author_id_fkey FOREIGN KEY (author_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table only public.stories add constraint stories_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.story_views add constraint story_views_story_id_fkey FOREIGN KEY (story_id) REFERENCES stories(id) ON DELETE CASCADE;
alter table only public.story_views add constraint story_views_viewer_id_fkey FOREIGN KEY (viewer_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table only public.think_reactions add constraint think_reactions_message_id_fkey FOREIGN KEY (message_id) REFERENCES shared_messages(id) ON DELETE CASCADE;
alter table only public.weekly_quiz_rewards add constraint weekly_quiz_rewards_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.weekly_quiz_rewards add constraint weekly_quiz_rewards_set_id_fkey FOREIGN KEY (set_id) REFERENCES quiz_sets(id) ON DELETE CASCADE;
alter table only public.widget_action_receipts add constraint widget_action_receipts_message_id_fkey FOREIGN KEY (message_id) REFERENCES shared_messages(id) ON DELETE SET NULL;
alter table only public.widget_action_receipts add constraint widget_action_receipts_token_id_fkey FOREIGN KEY (token_id) REFERENCES widget_action_tokens(id) ON DELETE CASCADE;
alter table only public.widget_action_tokens add constraint widget_action_tokens_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.widget_action_tokens add constraint widget_action_tokens_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table only public.widget_scriptable_installations add constraint widget_scriptable_installations_action_token_id_fkey FOREIGN KEY (action_token_id) REFERENCES widget_action_tokens(id) ON DELETE CASCADE;
alter table only public.widget_scriptable_installations add constraint widget_scriptable_installations_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.widget_scriptable_installations add constraint widget_scriptable_installations_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table only public.widget_scriptable_setup_codes add constraint widget_scriptable_setup_codes_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.widget_scriptable_setup_codes add constraint widget_scriptable_setup_codes_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table only public.widget_tokens add constraint widget_tokens_couple_id_fkey FOREIGN KEY (couple_id) REFERENCES couples(id) ON DELETE CASCADE;
alter table only public.widget_tokens add constraint widget_tokens_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
