-- US backend baseline: indexes
-- GENERATED by scripts/build-supabase-baseline.mjs from the committed
-- production capture (docs/us-2.0/F2A_1_PRODUCTION_CAPTURE*.json).
-- Do not edit by hand: regenerate. Never applied to production by F2A.1.
-- Indexes that do not back a constraint (pg_get_indexdef).

set check_function_bodies = off;
select pg_catalog.set_config('search_path', '"\$user", public, extensions', false);

CREATE INDEX activity_couple_idx ON public.activity USING btree (couple_id, created_at DESC);
CREATE INDEX bond_weekly_quests_lookup_idx ON public.bond_weekly_quests USING btree (couple_id, week_start, slot);
CREATE INDEX bond_weekly_quests_template_key_idx ON public.bond_weekly_quests USING btree (template_key);
CREATE UNIQUE INDEX bucket_items_calendar_entry_id_key ON public.bucket_items USING btree (calendar_entry_id) WHERE (calendar_entry_id IS NOT NULL);
CREATE INDEX bucket_items_couple_idx ON public.bucket_items USING btree (couple_id, created_at DESC);
CREATE INDEX calendar_entries_couple_allday_idx ON public.calendar_entries USING btree (couple_id, start_date) WHERE (is_all_day = true);
CREATE INDEX calendar_entries_couple_timed_idx ON public.calendar_entries USING btree (couple_id, starts_at) WHERE (is_all_day = false);
CREATE INDEX calendar_reminders_entry_idx ON public.calendar_reminders USING btree (entry_id);
CREATE INDEX calendar_reminders_pending_idx ON public.calendar_reminders USING btree (offset_minutes, recipient_id) WHERE (sent_at IS NULL);
CREATE INDEX conserva_couple_created_idx ON public.conserva_contributions USING btree (couple_id, created_at DESC);
CREATE INDEX conserva_recipient_created_idx ON public.conserva_contributions USING btree (conserved_by, created_at DESC);
CREATE INDEX couple_locations_couple_id_idx ON public.couple_locations USING btree (couple_id);
CREATE INDEX couple_locations_updated_at_idx ON public.couple_locations USING btree (updated_at DESC);
CREATE INDEX couple_questions_library_idx ON public.couple_questions USING btree (couple_id, created_at DESC) WHERE (archived_at IS NULL);
CREATE UNIQUE INDEX couple_questions_weekly_key ON public.couple_questions USING btree (couple_id, week_start) WHERE (origin = 'weekly'::text);
CREATE INDEX daily_answers_couple_question_idx ON public.daily_answers USING btree (couple_id, question_id);
CREATE INDEX daily_question_keepsakes_couple_date_idx ON public.daily_question_keepsakes USING btree (couple_id, question_date DESC);
CREATE INDEX daily_question_outcomes_couple_question_idx ON public.daily_question_outcomes USING btree (couple_id, question_id);
CREATE INDEX daily_question_reveal_states_question_idx ON public.daily_question_reveal_states USING btree (question_id);
CREATE INDEX daily_questions_template_id_idx ON public.daily_questions USING btree (template_id);
CREATE INDEX device_push_tokens_couple_id_idx ON public.device_push_tokens USING btree (couple_id);
CREATE INDEX device_push_tokens_user_id_idx ON public.device_push_tokens USING btree (user_id);
CREATE INDEX game_session_items_source_question_idx ON public.game_session_items USING btree (source_question_id) WHERE (source_question_id IS NOT NULL);
CREATE INDEX game_sessions_couple_recent_idx ON public.game_sessions USING btree (couple_id, started_at DESC);
CREATE UNIQUE INDEX game_sessions_v2_open_key ON public.game_sessions USING btree (couple_id, game_family) WHERE ((engine_version = 2) AND (completed_at IS NULL));
CREATE INDEX left_for_you_couple_created_idx ON public.left_for_you USING btree (couple_id, created_at DESC);
CREATE INDEX left_for_you_recipient_created_idx ON public.left_for_you USING btree (recipient_id, created_at DESC);
CREATE INDEX left_for_you_recipient_unseen_idx ON public.left_for_you USING btree (recipient_id, created_at DESC) WHERE (seen_at IS NULL);
CREATE INDEX left_for_you_unseen_created_idx ON public.left_for_you USING btree (created_at) WHERE (seen_at IS NULL);
CREATE UNIQUE INDEX left_for_you_uploaded_media_path_unique ON public.left_for_you USING btree (media_path) WHERE (kind = ANY (ARRAY['photo'::text, 'audio'::text, 'video'::text]));
CREATE INDEX living_provenance_bucket_item_idx ON public.living_provenance USING btree (source_bucket_item_id) WHERE (source_bucket_item_id IS NOT NULL);
CREATE INDEX living_provenance_completion_idx ON public.living_provenance USING btree (source_event_completion_id) WHERE (source_event_completion_id IS NOT NULL);
CREATE INDEX living_provenance_couple_idx ON public.living_provenance USING btree (couple_id);
CREATE INDEX moment_photos_couple_idx ON public.moment_photos USING btree (couple_id);
CREATE INDEX moment_photos_moment_position_idx ON public.moment_photos USING btree (moment_id, "position", created_at);
CREATE UNIQUE INDEX profiles_one_role_per_couple ON public.profiles USING btree (couple_id, role) WHERE (couple_id IS NOT NULL);
CREATE INDEX progression_events_rhythm_idx ON public.progression_events USING btree (couple_id, action_day DESC) WHERE (counts_rhythm = true);
CREATE INDEX push_event_log_created_idx ON public.push_event_log USING btree (created_at DESC);
CREATE INDEX push_subscriptions_couple_idx ON public.push_subscriptions USING btree (couple_id);
CREATE INDEX push_subscriptions_user_idx ON public.push_subscriptions USING btree (user_id);
CREATE INDEX quiz_responses_couple_set_idx ON public.quiz_responses USING btree (couple_id, set_id);
CREATE INDEX quiz_responses_couple_week_idx ON public.quiz_responses USING btree (couple_id, week_start, set_id);
CREATE UNIQUE INDEX quiz_responses_question_user_week_key ON public.quiz_responses USING btree (question_id, user_id, week_start);
CREATE INDEX relationship_milestones_couple_date_idx ON public.relationship_milestones USING btree (couple_id, milestone_date DESC);
CREATE INDEX shared_event_completions_couple_date_idx ON public.shared_event_completions USING btree (couple_id, occurrence_date DESC);
CREATE INDEX shared_events_couple_date_idx ON public.shared_events USING btree (couple_id, event_date, event_time);
CREATE INDEX messages_couple_idx ON public.shared_messages USING btree (couple_id, created_at DESC);
CREATE INDEX shared_messages_kind_created_idx ON public.shared_messages USING btree (kind, created_at DESC);
CREATE INDEX shared_messages_recipient_kind_created_idx ON public.shared_messages USING btree (recipient_id, kind, created_at DESC);
CREATE UNIQUE INDEX shared_messages_think_operation_idx ON public.shared_messages USING btree (sender_id, think_operation_id) WHERE ((kind = 'think'::text) AND (think_operation_id IS NOT NULL));
CREATE INDEX stories_author_created_idx ON public.stories USING btree (author_id, created_at DESC);
CREATE INDEX stories_couple_expires_idx ON public.stories USING btree (couple_id, expires_at DESC);
CREATE INDEX story_views_viewer_idx ON public.story_views USING btree (viewer_id, viewed_at DESC);
CREATE UNIQUE INDEX widget_action_tokens_active_device_idx ON public.widget_action_tokens USING btree (profile_id, device_id_hash, scope) WHERE (revoked_at IS NULL);
CREATE UNIQUE INDEX widget_scriptable_installations_active_device_idx ON public.widget_scriptable_installations USING btree (profile_id, device_id_hash) WHERE (revoked_at IS NULL);
CREATE INDEX widget_scriptable_installations_expiry_idx ON public.widget_scriptable_installations USING btree (expires_at) WHERE (revoked_at IS NULL);
CREATE INDEX widget_scriptable_installations_profile_idx ON public.widget_scriptable_installations USING btree (profile_id, created_at DESC);
CREATE INDEX widget_scriptable_setup_codes_profile_idx ON public.widget_scriptable_setup_codes USING btree (profile_id, created_at DESC);
CREATE INDEX widget_tokens_profile_idx ON public.widget_tokens USING btree (profile_id) WHERE (revoked_at IS NULL);
