-- US backend baseline: views
-- GENERATED by scripts/build-supabase-baseline.mjs from the committed
-- production capture (docs/us-2.0/F2A_1_PRODUCTION_CAPTURE*.json).
-- Do not edit by hand: regenerate. Never applied to production by F2A.1.

set check_function_bodies = off;
select pg_catalog.set_config('search_path', '"\$user", public, extensions', false);

create view public.relationship_event_history with (security_invoker=true) as
 SELECT 'shared_event_completion'::text AS source_kind,
    c.id AS source_ref,
    ('shared_event_completion:'::text || (c.id)::text) AS source_key,
    c.couple_id,
    c.event_id,
    c.occurrence_date,
    c.completed_at,
    c.completed_by,
    COALESCE(c.event_title_snapshot, e.title) AS title,
        CASE
            WHEN (c.event_title_snapshot IS NOT NULL) THEN 'snapshot'::text
            WHEN (e.id IS NOT NULL) THEN 'live'::text
            ELSE 'missing'::text
        END AS title_source,
    e.title AS current_title,
    p.target_ref AS moment_id
   FROM ((shared_event_completions c
     LEFT JOIN shared_events e ON (((e.id = c.event_id) AND (e.couple_id = c.couple_id))))
     LEFT JOIN living_provenance p ON (((p.source_kind = 'shared_event_completion'::text) AND (p.source_ref = c.id) AND (p.target_kind = 'moment'::text) AND (p.couple_id = c.couple_id))))
  WHERE (c.couple_id = private.current_couple_id());
