-- US backend baseline: triggers
-- GENERATED by scripts/build-supabase-baseline.mjs from the committed
-- production capture (docs/us-2.0/F2A_1_PRODUCTION_CAPTURE*.json).
-- Do not edit by hand: regenerate. Never applied to production by F2A.1.
-- pg_get_triggerdef output, including triggers on platform tables that call US functions.

set check_function_bodies = off;
select pg_catalog.set_config('search_path', '"\$user", public, extensions', false);

CREATE TRIGGER progression_quest_complete AFTER UPDATE OF completed_at ON public.bond_weekly_quests FOR EACH ROW EXECUTE FUNCTION private.progression_quest_trigger();
CREATE TRIGGER bucket_items_guard_delete BEFORE DELETE ON public.bucket_items FOR EACH ROW EXECUTE FUNCTION private.bucket_items_guard_delete();
CREATE TRIGGER bucket_items_guard_insert BEFORE INSERT ON public.bucket_items FOR EACH ROW EXECUTE FUNCTION private.bucket_items_guard_insert();
CREATE TRIGGER bucket_items_guard_update BEFORE UPDATE ON public.bucket_items FOR EACH ROW EXECUTE FUNCTION private.bucket_items_guard_update();
CREATE TRIGGER bucket_items_release_archived_link BEFORE UPDATE ON public.bucket_items FOR EACH ROW EXECUTE FUNCTION private.bucket_items_release_archived_link();
CREATE TRIGGER calendar_entries_guard_update BEFORE UPDATE ON public.calendar_entries FOR EACH ROW EXECUTE FUNCTION private.calendar_entries_guard_update();
CREATE TRIGGER calendar_entries_unschedule_bucket_items BEFORE DELETE ON public.calendar_entries FOR EACH ROW EXECUTE FUNCTION private.calendar_entries_unschedule_bucket_items();
CREATE TRIGGER progression_couples_xp AFTER UPDATE OF bond_xp ON public.couples FOR EACH ROW EXECUTE FUNCTION private.progression_couples_xp_trigger();
CREATE TRIGGER progression_daily_answer AFTER INSERT OR UPDATE OF answer ON public.daily_answers FOR EACH ROW EXECUTE FUNCTION private.progression_daily_trigger();
CREATE TRIGGER daily_question_keepsakes_guard_update BEFORE UPDATE ON public.daily_question_keepsakes FOR EACH ROW EXECUTE FUNCTION private.daily_question_keepsakes_guard_update();
CREATE TRIGGER game_session_items_immutable BEFORE UPDATE ON public.game_session_items FOR EACH ROW EXECUTE FUNCTION private.game_v2_items_immutable();
CREATE TRIGGER progression_game_complete AFTER UPDATE OF completed_at ON public.game_sessions FOR EACH ROW EXECUTE FUNCTION private.progression_game_trigger();
CREATE TRIGGER left_for_you_cleanup_eligibility BEFORE INSERT ON public.left_for_you FOR EACH ROW EXECUTE FUNCTION private.set_left_for_you_cleanup_eligible_at();
CREATE TRIGGER living_provenance_guard_update BEFORE UPDATE ON public.living_provenance FOR EACH ROW EXECUTE FUNCTION private.living_provenance_guard_update();
CREATE TRIGGER progression_moment_create AFTER INSERT ON public.moments FOR EACH ROW EXECUTE FUNCTION private.progression_moment_trigger();
CREATE TRIGGER progression_milestone_complete AFTER INSERT ON public.relationship_milestones FOR EACH ROW EXECUTE FUNCTION private.progression_milestone_trigger();
CREATE TRIGGER progression_event_complete AFTER INSERT ON public.shared_event_completions FOR EACH ROW EXECUTE FUNCTION private.progression_event_trigger();
CREATE TRIGGER shared_event_completions_title_snapshot BEFORE INSERT OR UPDATE ON public.shared_event_completions FOR EACH ROW EXECUTE FUNCTION private.shared_event_completions_title_snapshot();
CREATE TRIGGER shared_events_touch_updated_at BEFORE UPDATE ON public.shared_events FOR EACH ROW EXECUTE FUNCTION private.us_touch_updated_at();
CREATE TRIGGER progression_think_send AFTER INSERT ON public.shared_messages FOR EACH ROW EXECUTE FUNCTION private.progression_think_trigger();
