-- US backend baseline: row level security
-- GENERATED by scripts/build-supabase-baseline.mjs from the committed
-- production capture (docs/us-2.0/F2A_1_PRODUCTION_CAPTURE*.json).
-- Do not edit by hand: regenerate. Never applied to production by F2A.1.
-- RLS / FORCE RLS flags and every public and private policy.
-- Storage policies are in 85_storage.sql.

set check_function_bodies = off;
select pg_catalog.set_config('search_path', '"\$user", public, extensions', false);

alter table public.activity enable row level security;
alter table public.bond_quest_templates enable row level security;
alter table public.bond_weekly_quests enable row level security;
alter table public.bond_weekly_state enable row level security;
alter table public.bucket_items enable row level security;
alter table public.calendar_entries enable row level security;
alter table public.calendar_entries force row level security;
alter table public.calendar_reminders enable row level security;
alter table public.calendar_reminders force row level security;
alter table public.conserva_contributions enable row level security;
alter table public.conserva_contributions force row level security;
alter table public.couple_invites enable row level security;
alter table public.couple_locations enable row level security;
alter table public.couple_progression_preferences enable row level security;
alter table public.couple_progression_preferences force row level security;
alter table public.couple_questions enable row level security;
alter table public.couple_questions force row level security;
alter table public.couple_reward_unlocks enable row level security;
alter table public.couple_reward_unlocks force row level security;
alter table public.couples enable row level security;
alter table public.daily_answers enable row level security;
alter table public.daily_question_keepsakes enable row level security;
alter table public.daily_question_keepsakes force row level security;
alter table public.daily_question_outcomes enable row level security;
alter table public.daily_question_outcomes force row level security;
alter table public.daily_question_reveal_states enable row level security;
alter table public.daily_question_reveal_states force row level security;
alter table public.daily_question_templates enable row level security;
alter table public.daily_question_templates force row level security;
alter table public.daily_questions enable row level security;
alter table public.device_push_tokens enable row level security;
alter table public.game_session_answers enable row level security;
alter table public.game_session_answers force row level security;
alter table public.game_session_items enable row level security;
alter table public.game_session_items force row level security;
alter table public.game_session_sides enable row level security;
alter table public.game_session_sides force row level security;
alter table public.game_sessions enable row level security;
alter table public.game_sessions force row level security;
alter table public.game_v2_catalog enable row level security;
alter table public.game_v2_catalog force row level security;
alter table public.game_v2_cooldowns enable row level security;
alter table public.game_v2_cooldowns force row level security;
alter table public.game_v2_recipes enable row level security;
alter table public.game_v2_recipes force row level security;
alter table public.left_for_you enable row level security;
alter table public.left_for_you force row level security;
alter table public.living_provenance enable row level security;
alter table public.living_provenance force row level security;
alter table public.moment_photos enable row level security;
alter table public.moments enable row level security;
alter table public.moods enable row level security;
alter table public.notification_preferences enable row level security;
alter table public.partner_knowledge_attempts enable row level security;
alter table public.profiles enable row level security;
alter table public.progression_events enable row level security;
alter table public.progression_events force row level security;
alter table public.progression_reward_catalog enable row level security;
alter table public.progression_reward_catalog force row level security;
alter table public.progression_reward_views enable row level security;
alter table public.progression_reward_views force row level security;
alter table public.push_event_log enable row level security;
alter table public.push_subscriptions enable row level security;
alter table public.quiz_questions enable row level security;
alter table public.quiz_responses enable row level security;
alter table public.quiz_sets enable row level security;
alter table public.relationship_milestones enable row level security;
alter table public.shared_event_completions enable row level security;
alter table public.shared_events enable row level security;
alter table public.shared_messages enable row level security;
alter table public.stories enable row level security;
alter table public.story_views enable row level security;
alter table public.think_reactions enable row level security;
alter table public.think_reactions force row level security;
alter table public.weekly_quiz_rewards enable row level security;
alter table public.widget_action_receipts enable row level security;
alter table public.widget_action_tokens enable row level security;
alter table public.widget_scriptable_installations enable row level security;
alter table public.widget_scriptable_setup_codes enable row level security;
alter table public.widget_tokens enable row level security;

create policy activity_insert_same_couple on public.activity as permissive for insert to authenticated
  with check (((couple_id = private.current_couple_id()) AND (actor_id = auth.uid())));
create policy activity_read_same_couple on public.activity as permissive for select to authenticated
  using ((couple_id = private.current_couple_id()));
create policy bond_templates_read on public.bond_quest_templates as permissive for select to authenticated
  using ((active = true));
create policy bond_quests_select on public.bond_weekly_quests as permissive for select to authenticated
  using ((couple_id = private.current_couple_id()));
create policy bond_weekly_state_select on public.bond_weekly_state as permissive for select to authenticated
  using ((couple_id = private.current_couple_id()));
create policy bucket_delete_same_couple on public.bucket_items as permissive for delete to authenticated
  using ((couple_id = private.current_couple_id()));
create policy bucket_insert_same_couple on public.bucket_items as permissive for insert to authenticated
  with check (((couple_id = private.current_couple_id()) AND (created_by = auth.uid())));
create policy bucket_read_same_couple on public.bucket_items as permissive for select to authenticated
  using ((couple_id = private.current_couple_id()));
create policy bucket_update_same_couple on public.bucket_items as permissive for update to authenticated
  using ((couple_id = private.current_couple_id()))
  with check ((couple_id = private.current_couple_id()));
create policy calendar_entries_delete_personal on public.calendar_entries as permissive for delete to authenticated
  using (((entry_type = 'personal'::text) AND (couple_id = private.current_couple_id()) AND (owner_id = auth.uid())));
create policy calendar_entries_delete_shared on public.calendar_entries as permissive for delete to authenticated
  using (((entry_type = 'shared'::text) AND (couple_id = private.current_couple_id()) AND (created_by = auth.uid())));
create policy calendar_entries_insert_personal on public.calendar_entries as permissive for insert to authenticated
  with check (((entry_type = 'personal'::text) AND (couple_id = private.current_couple_id()) AND (created_by = auth.uid()) AND (owner_id = auth.uid())));
create policy calendar_entries_insert_shared on public.calendar_entries as permissive for insert to authenticated
  with check (((entry_type = 'shared'::text) AND (couple_id = private.current_couple_id()) AND (created_by = auth.uid()) AND (owner_id IS NULL)));
create policy calendar_entries_select_couple on public.calendar_entries as permissive for select to authenticated
  using ((couple_id = private.current_couple_id()));
create policy calendar_entries_update_personal on public.calendar_entries as permissive for update to authenticated
  using (((entry_type = 'personal'::text) AND (couple_id = private.current_couple_id()) AND (owner_id = auth.uid())))
  with check (((entry_type = 'personal'::text) AND (couple_id = private.current_couple_id()) AND (owner_id = auth.uid())));
create policy calendar_entries_update_shared on public.calendar_entries as permissive for update to authenticated
  using (((entry_type = 'shared'::text) AND (couple_id = private.current_couple_id()) AND (created_by = auth.uid())))
  with check (((entry_type = 'shared'::text) AND (couple_id = private.current_couple_id()) AND (created_by = auth.uid())));
create policy calendar_reminders_delete_requester on public.calendar_reminders as permissive for delete to authenticated
  using (((couple_id = private.current_couple_id()) AND ((requested_by = auth.uid()) OR (recipient_id = auth.uid()))));
create policy calendar_reminders_insert_couple on public.calendar_reminders as permissive for insert to authenticated
  with check (((couple_id = private.current_couple_id()) AND (requested_by = auth.uid()) AND (EXISTS ( SELECT 1
   FROM profiles p
  WHERE ((p.id = calendar_reminders.recipient_id) AND (p.couple_id = p.couple_id)))) AND (EXISTS ( SELECT 1
   FROM calendar_entries e
  WHERE ((e.id = calendar_reminders.entry_id) AND (e.couple_id = e.couple_id) AND ((e.entry_type = 'shared'::text) OR (e.owner_id = auth.uid())))))));
create policy calendar_reminders_select_couple on public.calendar_reminders as permissive for select to authenticated
  using ((couple_id = private.current_couple_id()));
create policy calendar_reminders_update_requester on public.calendar_reminders as permissive for update to authenticated
  using (((couple_id = private.current_couple_id()) AND (requested_by = auth.uid())))
  with check (((couple_id = private.current_couple_id()) AND (requested_by = auth.uid())));
create policy conserva_select_same_couple on public.conserva_contributions as permissive for select to authenticated
  using ((couple_id = private.current_couple_id()));
create policy couple_locations_insert_self on public.couple_locations as permissive for insert to authenticated
  with check (((user_id = ( SELECT auth.uid() AS uid)) AND (couple_id = private.current_couple_id())));
create policy couple_locations_select_same_couple on public.couple_locations as permissive for select to authenticated
  using ((couple_id = private.current_couple_id()));
create policy couple_locations_update_self on public.couple_locations as permissive for update to authenticated
  using (((user_id = ( SELECT auth.uid() AS uid)) AND (couple_id = private.current_couple_id())))
  with check (((user_id = ( SELECT auth.uid() AS uid)) AND (couple_id = private.current_couple_id())));
create policy couples_select_own on public.couples as permissive for select to authenticated
  using ((id = private.current_couple_id()));
create policy couples_update_own on public.couples as permissive for update to authenticated
  using ((id = private.current_couple_id()))
  with check ((id = private.current_couple_id()));
create policy daily_answers_insert_own on public.daily_answers as permissive for insert to authenticated
  with check (((user_id = auth.uid()) AND (couple_id = private.current_couple_id())));
create policy daily_answers_read_own on public.daily_answers as permissive for select to authenticated
  using ((user_id = auth.uid()));
create policy daily_answers_update_own on public.daily_answers as permissive for update to authenticated
  using ((user_id = auth.uid()))
  with check (((user_id = auth.uid()) AND (couple_id = private.current_couple_id())));
create policy daily_question_keepsakes_select_same_couple on public.daily_question_keepsakes as permissive for select to authenticated
  using ((couple_id = private.current_couple_id()));
create policy daily_question_outcomes_select_after_reveal on public.daily_question_outcomes as permissive for select to authenticated
  using (((couple_id = private.current_couple_id()) AND private.daily_question_reveal_ready(question_id)));
create policy daily_questions_read on public.daily_questions as permissive for select to authenticated
  using (true);
create policy device_push_tokens_delete_own on public.device_push_tokens as permissive for delete to authenticated
  using ((user_id = auth.uid()));
create policy device_push_tokens_select_own on public.device_push_tokens as permissive for select to authenticated
  using ((user_id = auth.uid()));
create policy left_for_you_insert_own on public.left_for_you as permissive for insert to authenticated
  with check (((couple_id = private.current_couple_id()) AND (sender_id = auth.uid()) AND (recipient_id <> sender_id) AND (seen_at IS NULL) AND (EXISTS ( SELECT 1
   FROM profiles partner
  WHERE ((partner.id = left_for_you.recipient_id) AND (partner.couple_id = private.current_couple_id())))) AND ((kind <> ALL (ARRAY['photo'::text, 'audio'::text, 'video'::text])) OR starts_with(media_path, ((((couple_id)::text || '/'::text) || (auth.uid())::text) || '/left/'::text))) AND ((kind <> 'music'::text) OR (NOT starts_with(media_path, ((((couple_id)::text || '/'::text) || (auth.uid())::text) || '/left/'::text))))));
create policy left_for_you_select_participants on public.left_for_you as permissive for select to authenticated
  using (((couple_id = private.current_couple_id()) AND ((auth.uid() = sender_id) OR (auth.uid() = recipient_id))));
create policy living_provenance_select_same_couple on public.living_provenance as permissive for select to authenticated
  using ((couple_id = private.current_couple_id()));
create policy moment_photos_delete_own on public.moment_photos as permissive for delete to authenticated
  using (((couple_id = private.current_couple_id()) AND (created_by = auth.uid())));
create policy moment_photos_insert_own on public.moment_photos as permissive for insert to authenticated
  with check (((couple_id = private.current_couple_id()) AND (created_by = auth.uid()) AND (EXISTS ( SELECT 1
   FROM moments m
  WHERE ((m.id = moment_photos.moment_id) AND (m.couple_id = private.current_couple_id()))))));
create policy moment_photos_select_same_couple on public.moment_photos as permissive for select to authenticated
  using (((couple_id = private.current_couple_id()) AND (EXISTS ( SELECT 1
   FROM moments m
  WHERE ((m.id = moment_photos.moment_id) AND (m.couple_id = private.current_couple_id()))))));
create policy moment_photos_update_own on public.moment_photos as permissive for update to authenticated
  using (((couple_id = private.current_couple_id()) AND (created_by = auth.uid())))
  with check (((couple_id = private.current_couple_id()) AND (created_by = auth.uid())));
create policy moments_delete_own on public.moments as permissive for delete to authenticated
  using (((couple_id = private.current_couple_id()) AND (created_by = auth.uid())));
create policy moments_insert_own on public.moments as permissive for insert to authenticated
  with check (((couple_id = private.current_couple_id()) AND (created_by = auth.uid())));
create policy moments_select_same_couple on public.moments as permissive for select to authenticated
  using ((couple_id = private.current_couple_id()));
create policy moments_update_own on public.moments as permissive for update to authenticated
  using (((couple_id = private.current_couple_id()) AND (created_by = auth.uid())))
  with check (((couple_id = private.current_couple_id()) AND (created_by = auth.uid())));
create policy moods_insert_own on public.moods as permissive for insert to authenticated
  with check (((couple_id = private.current_couple_id()) AND (user_id = auth.uid())));
create policy moods_read_same_couple on public.moods as permissive for select to authenticated
  using ((couple_id = private.current_couple_id()));
create policy moods_update_own on public.moods as permissive for update to authenticated
  using ((user_id = auth.uid()))
  with check (((couple_id = private.current_couple_id()) AND (user_id = auth.uid())));
create policy notification_preferences_insert_self on public.notification_preferences as permissive for insert to public
  with check ((user_id = auth.uid()));
create policy notification_preferences_select_self on public.notification_preferences as permissive for select to public
  using ((user_id = auth.uid()));
create policy notification_preferences_update_self on public.notification_preferences as permissive for update to public
  using ((user_id = auth.uid()))
  with check ((user_id = auth.uid()));
create policy partner_knowledge_attempts_read_own on public.partner_knowledge_attempts as permissive for select to public
  using ((user_id = auth.uid()));
create policy profiles_select_same_couple on public.profiles as permissive for select to authenticated
  using (((id = auth.uid()) OR (couple_id = private.current_couple_id())));
create policy profiles_update_self on public.profiles as permissive for update to authenticated
  using ((id = auth.uid()))
  with check ((id = auth.uid()));
create policy quiz_questions_read on public.quiz_questions as permissive for select to authenticated
  using (true);
create policy quiz_responses_read_own on public.quiz_responses as permissive for select to authenticated
  using ((user_id = auth.uid()));
create policy quiz_sets_read on public.quiz_sets as permissive for select to authenticated
  using (true);
create policy relationship_milestones_select_same_couple on public.relationship_milestones as permissive for select to public
  using ((couple_id = private.current_couple_id()));
create policy shared_event_completions_select_same_couple on public.shared_event_completions as permissive for select to public
  using ((couple_id = private.current_couple_id()));
create policy shared_events_delete_same_couple on public.shared_events as permissive for delete to authenticated
  using ((couple_id = private.current_couple_id()));
create policy shared_events_insert_same_couple on public.shared_events as permissive for insert to authenticated
  with check (((couple_id = private.current_couple_id()) AND (created_by = auth.uid())));
create policy shared_events_select_same_couple on public.shared_events as permissive for select to authenticated
  using ((couple_id = private.current_couple_id()));
create policy shared_events_update_same_couple on public.shared_events as permissive for update to authenticated
  using ((couple_id = private.current_couple_id()))
  with check ((couple_id = private.current_couple_id()));
create policy messages_insert_own on public.shared_messages as permissive for insert to authenticated
  with check (((couple_id = private.current_couple_id()) AND (sender_id = auth.uid()) AND (EXISTS ( SELECT 1
   FROM profiles p
  WHERE ((p.id = shared_messages.recipient_id) AND (p.couple_id = private.current_couple_id()))))));
create policy messages_read_own_couple on public.shared_messages as permissive for select to authenticated
  using (((couple_id = private.current_couple_id()) AND ((sender_id = auth.uid()) OR (recipient_id = auth.uid()))));
create policy messages_update_recipient on public.shared_messages as permissive for update to authenticated
  using ((recipient_id = auth.uid()))
  with check (((couple_id = private.current_couple_id()) AND (recipient_id = auth.uid())));
create policy stories_delete_own on public.stories as permissive for delete to authenticated
  using (((couple_id = ( SELECT private.current_couple_id() AS current_couple_id)) AND (author_id = ( SELECT auth.uid() AS uid))));
create policy stories_insert_own on public.stories as permissive for insert to authenticated
  with check (((couple_id = ( SELECT private.current_couple_id() AS current_couple_id)) AND (author_id = ( SELECT auth.uid() AS uid)) AND (expires_at <= (now() + '24:05:00'::interval)) AND (expires_at > now())));
create policy stories_select_same_couple on public.stories as permissive for select to authenticated
  using ((couple_id = ( SELECT private.current_couple_id() AS current_couple_id)));
create policy story_views_insert_self on public.story_views as permissive for insert to authenticated
  with check (((viewer_id = ( SELECT auth.uid() AS uid)) AND (EXISTS ( SELECT 1
   FROM stories s
  WHERE ((s.id = story_views.story_id) AND (s.couple_id = ( SELECT private.current_couple_id() AS current_couple_id)) AND (s.expires_at > now()))))));
create policy story_views_select_same_couple on public.story_views as permissive for select to authenticated
  using ((EXISTS ( SELECT 1
   FROM stories s
  WHERE ((s.id = story_views.story_id) AND (s.couple_id = ( SELECT private.current_couple_id() AS current_couple_id))))));
create policy think_reactions_select_couple_members on public.think_reactions as permissive for select to authenticated
  using ((EXISTS ( SELECT 1
   FROM shared_messages message
  WHERE ((message.id = think_reactions.message_id) AND (message.kind = 'think'::text) AND (message.couple_id = private.current_couple_id()) AND ((message.sender_id = auth.uid()) OR (message.recipient_id = auth.uid()))))));
create policy weekly_quiz_rewards_same_couple_select on public.weekly_quiz_rewards as permissive for select to authenticated
  using ((EXISTS ( SELECT 1
   FROM profiles p
  WHERE ((p.id = auth.uid()) AND (p.couple_id = weekly_quiz_rewards.couple_id)))));
