-- US backend baseline: realtime
-- GENERATED by scripts/build-supabase-baseline.mjs from the committed
-- production capture (docs/us-2.0/F2A_1_PRODUCTION_CAPTURE*.json).
-- Do not edit by hand: regenerate. Never applied to production by F2A.1.
-- Membership of publication supabase_realtime (exists on every Supabase project).

set check_function_bodies = off;
select pg_catalog.set_config('search_path', '"\$user", public, extensions', false);

alter publication supabase_realtime add table only public.bond_weekly_quests;
alter publication supabase_realtime add table only public.couple_locations;
alter publication supabase_realtime add table only public.couples;
alter publication supabase_realtime add table only public.daily_answers;
alter publication supabase_realtime add table only public.left_for_you;
alter publication supabase_realtime add table only public.moment_photos;
alter publication supabase_realtime add table only public.moments;
alter publication supabase_realtime add table only public.quiz_responses;
alter publication supabase_realtime add table only public.relationship_milestones;
alter publication supabase_realtime add table only public.shared_event_completions;
alter publication supabase_realtime add table only public.shared_events;
alter publication supabase_realtime add table only public.shared_messages;
alter publication supabase_realtime add table only public.stories;
alter publication supabase_realtime add table only public.story_views;
alter publication supabase_realtime add table only public.think_reactions;
