-- US backend baseline: cron
-- GENERATED by scripts/build-supabase-baseline.mjs from the committed
-- production capture (docs/us-2.0/F2A_1_PRODUCTION_CAPTURE*.json).
-- Do not edit by hand: regenerate. Never applied to production by F2A.1.
-- SOURCE REPRESENTATION of the production pg_cron jobs, in production job order.
-- WARNING: the commands call the production project URL and read vault keys by
-- name. Apply only to production-equivalent environments; a staging rebuild must
-- substitute its own URL first (F2A D9). Vault secret VALUES are never in the repo.

select cron.schedule('us-monthiversary-hourly', '5 * * * *', $cron$
      select net.http_post(
        url := 'https://iiakdfsxpywdkxravqjh.supabase.co/functions/v1/monthiversary-job',
        headers := jsonb_build_object(
          'Content-Type','application/json',
          'x-us-cron-key',(select decrypted_secret from vault.decrypted_secrets where name='us_monthiversary_cron_key' limit 1)
        ),
        body := '{}'::jsonb
      );
    $cron$);
select cron.schedule('us-widget-scriptable-state-expiry', '* * * * *', $cron$
    update public.widget_tokens as state_token
    set revoked_at = now()
    from public.widget_scriptable_installations as installation
    where state_token.token_hash = installation.state_token_hash
      and installation.expires_at <= now()
      and installation.revoked_at is null
      and state_token.revoked_at is null;
  $cron$);
select cron.schedule('us-calendar-reminders-dispatch', '* * * * *', $cron$
        select net.http_post(
          url := 'https://iiakdfsxpywdkxravqjh.supabase.co/functions/v1/calendar-reminders-worker',
          headers := jsonb_build_object(
            'Content-Type','application/json',
            'x-us-cron-key',(select decrypted_secret from vault.decrypted_secrets where name = 'us_calendar_reminders_cron_key' limit 1)
          ),
          body := '{}'::jsonb
        );
      $cron$);
select cron.schedule('us-left-for-you-push-sweep', '* * * * *', $cron$
        select net.http_post(
          url := 'https://iiakdfsxpywdkxravqjh.supabase.co/functions/v1/left-for-you-push-worker',
          headers := jsonb_build_object(
            'Content-Type','application/json',
            'x-us-cron-key',(select decrypted_secret from vault.decrypted_secrets where name = 'us_left_for_you_push_cron_key' limit 1)
          ),
          body := '{}'::jsonb
        );
      $cron$);
select cron.schedule('us-daily-question-materialize', '1 * * * *', $cron$select private.materialize_daily_question(private.daily_question_day(now()))$cron$);
select cron.schedule('us-daily-question-push', '*/10 * * * *', $cron$
        with today as (
          select private.materialize_daily_question(private.daily_question_day(now())) as question
        )
        select net.http_post(
          url := 'https://iiakdfsxpywdkxravqjh.supabase.co/functions/v1/daily-question-push-worker',
          headers := jsonb_build_object(
            'Content-Type','application/json',
            'x-us-cron-key',(select decrypted_secret from vault.decrypted_secrets where name = 'us_daily_question_push_cron_key' limit 1)
          ),
          body := '{}'::jsonb
        )
        from today;
      $cron$);
select cron.schedule('us-game-v2-push', '*/10 * * * *', $cron$
        select net.http_post(
          url := 'https://iiakdfsxpywdkxravqjh.supabase.co/functions/v1/game-v2-push-worker',
          headers := jsonb_build_object(
            'Content-Type','application/json',
            'x-us-cron-key',(select decrypted_secret from vault.decrypted_secrets where name = 'us_game_v2_push_cron_key' limit 1)
          ),
          body := '{}'::jsonb
        );
      $cron$);
