(() => {
'use strict'; if(window.__usFix5Installed)return; window.__usFix5Installed=true;
const partnerName=()=>window.usProfile?.role==='francesco'?'Bea':'Francesco';
function setTodayDate(){const el=document.getElementById('todayDateLabel');if(!el)return;const raw=new Intl.DateTimeFormat('it-IT',{weekday:'long',day:'numeric',month:'long'}).format(new Date());el.textContent=raw.charAt(0).toUpperCase()+raw.slice(1)}
function renderTodayPriority(){const card=document.getElementById('todayFocusCard'),stateEl=document.getElementById('todayFocusState'),title=document.getElementById('todayFocusTitle'),text=document.getElementById('todayFocusText');if(!card||!stateEl||!title||!text)return;const st=window.todayState;if(!window.usProfile||st===undefined){card.dataset.state='loading';stateEl.textContent='SINCRONIZZO';title.textContent='Vediamo cosa c’è oggi';text.textContent='Sto aggiornando il vostro spazio privato.';return}if(!window.todayQuestion||!st){card.dataset.state='quiet';stateEl.textContent='OGGI';title.textContent='Per ora tutto tranquillo';text.textContent='La prossima domanda arriverà qui appena sarà disponibile.';return}if(st.both_answered){card.dataset.state='reveal';stateEl.textContent='SBLOCCATO';title.textContent='Avete un momento da aprire';text.textContent='Le vostre risposte sono pronte. Aprile quando vuoi.';return}if(st.my_answer){card.dataset.state='waiting';stateEl.textContent='IN ATTESA';title.textContent='Hai fatto la tua parte';text.textContent=`Ora aspettiamo ${partnerName()}. Ti avviso quando il confronto è pronto.`;return}card.dataset.state='todo';stateEl.textContent='DA FARE';title.textContent='C’è una domanda per te';text.textContent=`Rispondi senza vedere ${partnerName()}: il momento si sblocca solo dopo.`}
function renderThinkQuickText(){const out=document.getElementById('thinkQuickText');if(!out)return;const received=document.getElementById('thinkLastReceived')?.textContent?.trim();out.textContent=received&&!/Ancora nessun/i.test(received)?received:`Invia un segnale discreto a ${partnerName()}`}
function decorateBond(){const xp=document.getElementById('bondTotalXp');if(xp)xp.textContent=xp.textContent.replace(/XP\s+totali/i,'XP condivisi');document.querySelectorAll('#bondQuestList .bond-quest').forEach(q=>{const people=[...q.querySelectorAll('.quest-confirmers > span')],status=q.querySelector('.quest-confirmers small');if(!status||people.length<2)return;const missing=people.filter(el=>!el.classList.contains('checked'));status.textContent=!missing.length?'Completata insieme':missing.length===1?`Manca ${missing[0].textContent.replace('✓','').trim()}`:'Da confermare entrambi'})}
function normalizeQuizTone(state){if(!state)return;const title=document.getElementById('scoreText'),sub=document.getElementById('scoreSub');if(!title||!sub)return;if(state.both_complete){const score=Number(state.score||0),total=Number(state.total||10),ratio=total?score/total:0;title.textContent=ratio>=.85?'Avete trovato molti punti in comune.':ratio>=.6?'Un buon mix di affinità e sorprese.':ratio>=.4?'Qui avete scoperto parecchie sfumature diverse.':'Questo set vi ha dato parecchio di cui parlare.';sub.textContent='I punti in comune aggiungono XP al percorso. Sotto trovi solo le differenze interessanti da confrontare.';const mt=document.querySelector('#quizMatches .quiz-match-title');if(mt)mt.textContent='Dove vi siete sorpresi'}else if(state.my_complete){title.textContent='Hai finito il tuo lato.';sub.textContent=`Il confronto si apre quando anche ${partnerName()} completa il set.`}}
function wrapAsync(name,after){const original=window[name];if(typeof original!=='function'||original.__fix5Wrapped)return;const wrapped=async function(...args){const r=await original.apply(this,args);try{after(...args)}catch(_){}return r};wrapped.__fix5Wrapped=true;window[name]=wrapped}
function wire(){wrapAsync('hydrateToday',renderTodayPriority);wrapAsync('hydrateBond',decorateBond);wrapAsync('hydrateThink',renderThinkQuickText);const sq=window.showQuizState;if(typeof sq==='function'&&!sq.__fix5Wrapped){const w=function(state,...rest){const r=sq.call(this,state,...rest);setTimeout(()=>normalizeQuizTone(state),0);return r};w.__fix5Wrapped=true;window.showQuizState=w}const originalGo=window.go;if(typeof originalGo==='function'&&!originalGo.__fix5Wrapped){const w=function(id,options={}){const target=id==='think'?'home':id;const r=originalGo.call(this,target,options);if(target==='bond'&&window.usProfile)setTimeout(()=>{window.hydrateThink?.().catch?.(()=>{});decorateBond()},40);if(target==='home')setTimeout(renderTodayPriority,40);return r};w.__fix5Wrapped=true;window.go=w}}
function observe(){const bond=document.getElementById('bondQuestList'),think=document.querySelector('.fix5-think-history-section');const ob=new MutationObserver(rs=>{let b=false,t=false;for(const r of rs){const el=r.target instanceof Element?r.target:r.target?.parentElement;if(!el)continue;if(bond?.contains(el)||el===bond)b=true;if(think?.contains(el)||el===think)t=true}if(b)decorateBond();if(t)renderThinkQuickText()});ob.observe(document.body,{subtree:true,childList:true,characterData:true})}
setTodayDate();renderTodayPriority();renderThinkQuickText();wire();observe();setTimeout(()=>{renderTodayPriority();renderThinkQuickText();decorateBond()},900);document.addEventListener('visibilitychange',()=>{if(!document.hidden){setTodayDate();setTimeout(()=>{renderTodayPriority();renderThinkQuickText();decorateBond()},120)}});console.info('[US] FIX 5 · US 1.0 visual layer attivo');
})();