// F2A.2 schema digest: ONE read-only block that runs every F2A.1 capture
// SELECT inside the database and returns only md5(result::text) per block,
// plus the full ledger listing. Run before and after the ledger repair: equal
// digests prove the repair changed nothing but supabase_migrations.
// The ledger is left out of the digest on purpose (c01.ledger and
// c10.ledger_sql read schema_migrations, which the repair rewrites).
const { captureQueries, aliasOf } = require('./queries.cjs');

const LEDGER_KEYS = { c01: 'ledger', c10: 'ledger_sql' };

function digestSql() {
  const queries = captureQueries();
  const parts = Object.entries(queries).map(([label, sql]) => {
    const alias = aliasOf(sql);
    const value = LEDGER_KEYS[label] ? `(q.${alias} - '${LEDGER_KEYS[label]}')` : `q.${alias}`;
    const inner = sql.split('\n').map((l) => `      ${l}`).join('\n');
    return `    '${label}', (select md5(${value}::text) from (\n${inner}\n    ) q)`;
  });
  return `-- US 2.0 F2A.2 — read-only schema digest, run before AND after the ledger repair.
--
-- GENERATED by scripts/build-supabase-baseline.mjs from
-- docs/us-2.0/F2A_1_PRODUCTION_CAPTURE.sql: every capture block runs inside
-- the database and only md5(result::text) comes back. The ledger is listed in
-- full (version, name, statement count, length, md5) and excluded from the
-- digest. Nothing writes. Nothing reads a vault value.
--
-- How to run: this is ONE block. Run it through the Supabase connector
-- (execute_sql) or the SQL Editor and copy the single JSON cell. Save as
--   docs/us-2.0/F2A_2_SCHEMA_DIGEST_PRE.json   (before the repair)
--   docs/us-2.0/F2A_2_SCHEMA_DIGEST_POST.json  (after the repair)
-- with {"captured_at": ..., "project_id": ..., "mode": "production-read-only",
--       "blocks": {"d01": {"text": <result>}}}.

begin transaction read only;
set local statement_timeout = '120s';

-- d01. Schema digest and ledger.
select jsonb_build_object(
  'digest', jsonb_build_object(
${parts.join(',\n')}
  ),
  'ledger', (select jsonb_agg(jsonb_build_object('v', version, 'n', name,
                'stmts', coalesce(array_length(statements, 1), 0),
                'len', coalesce(length(array_to_string(statements, E'\\n')), 0),
                'md5', md5(coalesce(array_to_string(statements, E'\\n'), ''))) order by version)
             from supabase_migrations.schema_migrations)
) as f2a2_d01_digest;

rollback;
`;
}

module.exports = { digestSql, LEDGER_KEYS };
