// The single US 2.0 baseline migration (F2A.2 step 4): the generated
// supabase/baseline files in MANIFEST order, without 00_extensions.sql
// (platform-managed) and without 90_cron.sql (stays a source file until F2C
// parametrises the project URL). It is the only executable migration up to
// BASELINE_VERSION; the 47 earlier files are history in
// supabase/migrations_history/ and never run again.
const path = require('node:path');
const crypto = require('node:crypto');

// One new version greater than every production ledger version (tip
// 20261003200000, F1C) at the time of F2A.2.
const BASELINE_VERSION = '20261004000000';
const BASELINE_NAME = 'us_2_0_baseline';
const BASELINE_FILE = `${BASELINE_VERSION}_${BASELINE_NAME}.sql`;
const BASELINE_PATH = path.join('supabase/migrations', BASELINE_FILE);
const EXCLUDED = new Set(['00_extensions.sql', '90_cron.sql']);

function baselineMigration(files) {
  const manifest = JSON.parse(files['MANIFEST.json']);
  const parts = manifest.apply_order.filter((name) => !EXCLUDED.has(name));
  const out = [
    `-- ${BASELINE_FILE}`,
    '-- US 2.0 baseline: the production schema at ledger tip 20261003200000 (F1C),',
    '-- captured read-only in F2A.1 and generated by scripts/build-supabase-baseline.mjs.',
    '-- Do not edit by hand: regenerate from the capture.',
    '--',
    '-- Production already has every object below. F2A.2 records this version as',
    '-- applied there (migration repair), so it never runs on production. It runs',
    '-- only on a new, empty Supabase project.',
    '--',
    `-- Excluded: ${[...EXCLUDED].join(', ')} (see supabase/baseline/).`,
    `-- Parts (sha256 of each supabase/baseline file):`,
    ...parts.map((name) => `--   ${name} ${crypto.createHash('sha256').update(files[name]).digest('hex')}`),
    '',
  ];
  for (const name of parts) out.push(`-- ==== supabase/baseline/${name}`, files[name].replace(/\n+$/, ''), '');
  out.push('reset check_function_bodies;', 'reset search_path;', '');
  return out.join('\n');
}

module.exports = { BASELINE_VERSION, BASELINE_NAME, BASELINE_FILE, BASELINE_PATH, EXCLUDED, baselineMigration };
