-- 20261006200000_native_notifications_v1.sql
-- Native Notifications V1: native push registration per physical app
-- installation (docs/native/NATIVE_NOTIFICATIONS_V1.md). Forward-only, newer
-- than every earlier migration. Nothing here sends a notification.
--
--   * public.device_push_tokens (baseline, retired since F1B, never wired) is
--     reshaped into "one row per installation": installation_id, provider
--     (fcm | apns), APNs environment, token_updated_at. It must be EMPTY: the
--     preconditions abort otherwise (the read-only pack
--     docs/native/NATIVE_NOTIFICATIONS_V1_PREFLIGHT.sql shows the count first).
--   * Client roles lose every table privilege and both legacy policies: tokens
--     are reachable only through the two RPCs below and by the service role
--     (the Edge dispatcher).
--   * register_native_push_device: identity from auth.uid() only, a real
--     non-anonymous auth user, a profile and a current couple; bounded token
--     shape per provider; the same token on another installation is removed
--     (token moved). An installation id already owned by another account is
--     never taken over: auth.uid() remains authoritative.
--   * unregister_native_push_device: removes ONE installation only when it is
--     owned by auth.uid(). Other users' and other devices' rows are untouched.
--     Offline logout still unregisters at the OS/provider and rotates the
--     installation id; a stale server row is later pruned on invalid-token.
--   * register_push_token(text,text) (RETIRED F1B, incompatible shape) is dropped.
--
-- Fails closed: preconditions abort before any change, the self-check aborts
-- if a postcondition does not hold. Re-applying it changes nothing.

do $n2_pre$
declare
  rows_present bigint;
begin
  if to_regclass('public.device_push_tokens') is null then
    raise exception 'N2: public.device_push_tokens missing; production is not in the baseline state';
  end if;
  if not exists (select 1 from information_schema.columns
                 where table_schema = 'public' and table_name = 'device_push_tokens' and column_name = 'installation_id') then
    select count(*) into rows_present from public.device_push_tokens;
    if rows_present > 0 then
      raise exception 'N2: device_push_tokens holds % legacy row(s) without an installation id; review them before applying', rows_present;
    end if;
  end if;
end
$n2_pre$;

-- Table ---------------------------------------------------------------------
alter table public.device_push_tokens add column if not exists installation_id uuid;
alter table public.device_push_tokens add column if not exists provider text;
alter table public.device_push_tokens add column if not exists apns_environment text;
alter table public.device_push_tokens add column if not exists token_updated_at timestamp with time zone;
alter table public.device_push_tokens alter column installation_id set not null;
alter table public.device_push_tokens alter column provider set not null;
alter table public.device_push_tokens alter column token_updated_at set default now();
alter table public.device_push_tokens alter column token_updated_at set not null;

alter table public.device_push_tokens drop constraint if exists device_push_tokens_installation_id_key;
alter table public.device_push_tokens add constraint device_push_tokens_installation_id_key unique (installation_id);
alter table public.device_push_tokens drop constraint if exists device_push_tokens_provider_check;
alter table public.device_push_tokens add constraint device_push_tokens_provider_check check (
  (platform = 'android' and provider = 'fcm' and apns_environment is null)
  or (platform = 'ios' and provider = 'apns' and apns_environment is not null and apns_environment in ('development', 'production'))
);
alter table public.device_push_tokens drop constraint if exists device_push_tokens_token_shape_check;
alter table public.device_push_tokens add constraint device_push_tokens_token_shape_check check (
  (provider = 'fcm' and length(token) between 32 and 4096 and token ~ '^[A-Za-z0-9_:-]+$')
  or (provider = 'apns' and length(token) between 64 and 200 and token ~ '^[0-9a-f]+$')
);

comment on table public.device_push_tokens is
  'Native Notifications V1: one native push registration per app installation (FCM on Android, APNs on iOS). No client access; RPCs + service role only.';
comment on column public.device_push_tokens.installation_id is
  'Random UUID generated by the app installation (not a hardware identifier). Rotated by the app at logout.';

-- No direct client access ---------------------------------------------------
drop policy if exists device_push_tokens_delete_own on public.device_push_tokens;
drop policy if exists device_push_tokens_select_own on public.device_push_tokens;
alter table public.device_push_tokens enable row level security;
alter table public.device_push_tokens force row level security;
revoke all on table public.device_push_tokens from public, anon, authenticated;
grant select, insert, update, delete on table public.device_push_tokens to service_role;

drop function if exists public.register_push_token(text, text);

-- RPCs -----------------------------------------------------------------------
create or replace function public.register_native_push_device(
  target_installation_id uuid,
  target_platform text,
  target_provider text,
  target_token text,
  target_environment text default null,
  target_retired_installation_id uuid default null
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  uid uuid := auth.uid();
  cid uuid;
  clean_token text := btrim(coalesce(target_token, ''));
  env text := nullif(btrim(coalesce(target_environment, '')), '');
  row_id uuid;
begin
  if uid is null then raise exception using errcode = '42501', message = 'authentication required'; end if;
  if not exists (select 1 from auth.users u where u.id = uid and not coalesce(u.is_anonymous, false)) then
    raise exception using errcode = '42501', message = 'account required';
  end if;
  select p.couple_id into cid from public.profiles p where p.id = uid;
  if cid is null or not exists (select 1 from public.couples c where c.id = cid) then
    raise exception using errcode = '42501', message = 'couple membership required';
  end if;
  if target_installation_id is null then raise exception using errcode = '22023', message = 'installation_invalid'; end if;
  if target_platform is null or target_provider is null then raise exception using errcode = '22023', message = 'platform_invalid'; end if;
  if not ((target_platform = 'android' and target_provider = 'fcm' and env is null)
       or (target_platform = 'ios' and target_provider = 'apns' and env is not null and env in ('development', 'production'))) then
    raise exception using errcode = '22023', message = 'platform_invalid';
  end if;
  if not ((target_provider = 'fcm' and length(clean_token) between 32 and 4096 and clean_token ~ '^[A-Za-z0-9_:-]+$')
       or (target_provider = 'apns' and length(clean_token) between 64 and 200 and clean_token ~ '^[0-9a-f]+$')) then
    raise exception using errcode = '22023', message = 'token_invalid';
  end if;

  -- Best-effort cleanup of an offline-retired installation. SECURITY DEFINER
  -- never treats the UUID itself as authorization: only this authenticated
  -- user's stale row may be removed. A retired row belonging to a previous
  -- account remains harmless because the native token was unregistered at
  -- logout and is pruned when the provider reports it invalid.
  if target_retired_installation_id is not null and target_retired_installation_id <> target_installation_id then
    delete from public.device_push_tokens d
    where d.installation_id = target_retired_installation_id
      and d.user_id = uid;
  end if;
  -- The provider token may move between installations of the SAME account
  -- (reinstall / restored app data). A token string is not authorization and
  -- can never be used to delete or take over another user's row.
  delete from public.device_push_tokens d
  where d.token = clean_token
    and d.installation_id <> target_installation_id
    and d.user_id = uid;

  insert into public.device_push_tokens as d
    (user_id, couple_id, installation_id, token, platform, provider, apns_environment, created_at, last_seen_at, token_updated_at)
  values (uid, cid, target_installation_id, clean_token, target_platform, target_provider, env, now(), now(), now())
  on conflict (installation_id) do update set
    couple_id = excluded.couple_id,
    token = excluded.token,
    platform = excluded.platform,
    provider = excluded.provider,
    apns_environment = excluded.apns_environment,
    last_seen_at = now(),
    token_updated_at = case when d.token is distinct from excluded.token then now() else d.token_updated_at end
  where d.user_id = uid
  returning d.id into row_id;

  if row_id is null then
    raise exception using errcode = '42501', message = 'installation owned by another account';
  end if;

  return jsonb_build_object('active', true, 'platform', target_platform, 'provider', target_provider);
end;
$$;

create or replace function public.unregister_native_push_device(target_installation_id uuid) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  removed integer := 0;
begin
  if auth.uid() is null then raise exception using errcode = '42501', message = 'authentication required'; end if;
  if target_installation_id is null then return jsonb_build_object('removed', false); end if;
  delete from public.device_push_tokens d
  where d.installation_id = target_installation_id
    and d.user_id = auth.uid();
  get diagnostics removed = row_count;
  return jsonb_build_object('removed', removed > 0);
end;
$$;

comment on function public.register_native_push_device(uuid, text, text, text, text, uuid) is
  'Native Notifications V1: registers this app installation''s FCM/APNs token for auth.uid() in its current couple.';
comment on function public.unregister_native_push_device(uuid) is
  'Native Notifications V1: removes one installation registration only when it belongs to auth.uid().';

revoke all on function public.register_native_push_device(uuid, text, text, text, text, uuid) from public, anon;
revoke all on function public.unregister_native_push_device(uuid) from public, anon;
grant execute on function public.register_native_push_device(uuid, text, text, text, text, uuid) to authenticated;
grant execute on function public.unregister_native_push_device(uuid) to authenticated;

-- (PostgreSQL regex repetition counts stop at 255: lengths are checked apart.)

-- Self-check ------------------------------------------------------------------
do $n2_post$
begin
  if has_table_privilege('authenticated', 'public.device_push_tokens', 'SELECT')
     or has_table_privilege('authenticated', 'public.device_push_tokens', 'INSERT')
     or has_table_privilege('authenticated', 'public.device_push_tokens', 'UPDATE')
     or has_table_privilege('authenticated', 'public.device_push_tokens', 'DELETE')
     or has_table_privilege('anon', 'public.device_push_tokens', 'SELECT')
     or has_table_privilege('anon', 'public.device_push_tokens', 'INSERT')
     or has_table_privilege('anon', 'public.device_push_tokens', 'UPDATE')
     or has_table_privilege('anon', 'public.device_push_tokens', 'DELETE') then
    raise exception 'N2: a client role can still read or write device_push_tokens';
  end if;
  if has_function_privilege('anon', 'public.register_native_push_device(uuid,text,text,text,text,uuid)', 'EXECUTE')
     or has_function_privilege('anon', 'public.unregister_native_push_device(uuid)', 'EXECUTE') then
    raise exception 'N2: anon can execute a native push RPC';
  end if;
  if not has_function_privilege('authenticated', 'public.register_native_push_device(uuid,text,text,text,text,uuid)', 'EXECUTE')
     or not has_function_privilege('authenticated', 'public.unregister_native_push_device(uuid)', 'EXECUTE') then
    raise exception 'N2: authenticated lost EXECUTE on a native push RPC';
  end if;
  if to_regprocedure('public.register_push_token(text,text)') is not null then
    raise exception 'N2: the retired register_push_token still exists';
  end if;
  if not exists (select 1 from pg_constraint where conrelid = 'public.device_push_tokens'::regclass and conname = 'device_push_tokens_installation_id_key') then
    raise exception 'N2: device_push_tokens_installation_id_key missing';
  end if;
end
$n2_post$;
