-- M11C — Game V2 context: explicit US-context adapters, curated recipes with
-- provenance, longitudinal resurfacing and perspective rotation.
--
-- Additive on top of M11B (20260930150000_m11b_game_v2_core.sql); apply the
-- two together. Nothing here writes to the sources it reads, and no adapter
-- reads Daily Question answers or Left for You content:
--   da_vivere_idea / da_vivere_lived  public.bucket_items (shared list)
--   calendar_upcoming / calendar_past public.calendar_entries, entry_type
--                                     'shared' only (personal entries never)
--   moment                            public.moments (shared), caption only
--   conservati                        public.conserva_contributions COUNT and
--                                     timestamp only, never the kept item
--   longitudinal                      the couple's own revealed Game V2 answers
-- Every candidate is materialized as an immutable item snapshot with its
-- provenance in game_session_items.context; a source changed or deleted later
-- never rewrites a played round.
--
-- Bond XP is deliberately NOT awarded: no Bond XP writer exists in
-- the repository to reuse safely, so Game V2 defers it (decision log).

-- ---------------------------------------------------------------------------
-- 1. Curated recipes (editorial authority for context prompts).
-- ---------------------------------------------------------------------------

create table public.game_v2_recipes (
  id text primary key check (id ~ '^[a-z_]+-[0-9]{3}$'),
  version integer not null default 1 check (version > 0),
  adapter text not null check (adapter in ('da_vivere_idea', 'da_vivere_lived', 'calendar_upcoming',
    'calendar_past', 'moment', 'conservati', 'longitudinal')),
  family text check (family is null or family = any (private.game_v2_families())),
  mechanic text not null default 'reciprocal' check (mechanic = 'reciprocal'),
  answer_kind text not null check (answer_kind in ('open', 'choice')),
  question_text text not null check (char_length(btrim(question_text)) between 12 and 240
    or question_text = '{previous_question}'),
  options jsonb not null default '[]'::jsonb,
  depth smallint not null check (depth between 1 and 3),
  topic text not null check (topic ~ '^ctx_[a-z_]+$'),
  cooldown_class text not null references public.game_v2_cooldowns(cooldown_class),
  kind_label text not null check (char_length(btrim(kind_label)) between 3 and 40),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  check (split_part(id, '-', 1) = adapter),
  -- A longitudinal item keeps the family of the prompt it resurfaces.
  check ((adapter = 'longitudinal') = (family is null)),
  check (adapter <> 'longitudinal' or (question_text = '{previous_question}' and answer_kind = 'open'
    and cooldown_class = 'longitudinal')),
  check (adapter = 'longitudinal' or cooldown_class = 'context'),
  check (adapter not in ('da_vivere_idea', 'da_vivere_lived', 'calendar_upcoming', 'calendar_past', 'moment')
    or question_text like '%{title}%'),
  check (case when jsonb_typeof(options) = 'array' then
    (answer_kind = 'open' and jsonb_array_length(options) = 0) or
    (answer_kind = 'choice' and jsonb_array_length(options) between 2 and 4)
    else false end)
);

comment on table public.game_v2_recipes is
  'M11C curated Game V2 context recipes. Source of truth: supabase/game-v2/recipes/<adapter>.json (generated seed). Server-only.';

alter table public.game_v2_recipes enable row level security;
alter table public.game_v2_recipes force row level security;
revoke all on public.game_v2_recipes from public, anon, authenticated;

-- game-v2-recipes:begin (generated by scripts/build-game-v2-catalog-sql.mjs recipes from supabase/game-v2/recipes; do not edit by hand)
insert into public.game_v2_recipes (id, version, adapter, family, answer_kind, question_text, options, depth, topic, cooldown_class, kind_label) values
  ('calendar_past-001', 1, 'calendar_past', 'rivivete', 'open', '«{title}», {when}: qual è il dettaglio che ricordi meglio?', '[]'::jsonb, 1, 'ctx_passato_dettaglio', 'context', 'Dal calendario'),
  ('calendar_past-002', 1, 'calendar_past', 'rivivete', 'open', 'Ripensando a «{title}», {when}, c’è qualcosa di quella giornata che non ti ho mai raccontato?', '[]'::jsonb, 2, 'ctx_passato_non_detto', 'context', 'Dal calendario'),
  ('calendar_upcoming-001', 1, 'calendar_upcoming', 'confrontatevi', 'open', 'Di «{title}», il {date}, qual è la parte che aspetti di più?', '[]'::jsonb, 1, 'ctx_evento_attesa', 'context', 'Nel calendario'),
  ('calendar_upcoming-002', 1, 'calendar_upcoming', 'e_se', 'open', 'Se «{title}» andasse ancora meglio del previsto, cosa sarebbe successo?', '[]'::jsonb, 2, 'ctx_evento_meglio', 'context', 'Nel calendario'),
  ('conservati-001', 1, 'conservati', 'rivivete', 'open', 'Tra le cose che abbiamo conservato, quale rileggeresti stasera, e perché proprio quella?', '[]'::jsonb, 2, 'ctx_conservati_rileggere', 'context', 'Dai Conservati'),
  ('da_vivere_idea-001', 1, 'da_vivere_idea', 'e_se', 'open', 'Se potessimo fare «{title}» questo fine settimana, senza organizzare niente, come immagini quella giornata?', '[]'::jsonb, 1, 'ctx_idea_immaginare', 'context', 'Da vivere'),
  ('da_vivere_idea-002', 1, 'da_vivere_idea', 'confrontatevi', 'choice', '«{title}»: per te è una cosa da preparare con cura o da vivere all’improvviso?', '["Da preparare con cura","Da vivere all’improvviso","Un po’ e un po’"]'::jsonb, 1, 'ctx_idea_stile', 'context', 'Da vivere'),
  ('da_vivere_idea-003', 1, 'da_vivere_idea', 'e_se', 'open', 'Quando arriverà il momento di «{title}», cosa speri che ti resti?', '[]'::jsonb, 2, 'ctx_idea_aspettativa', 'context', 'Da vivere'),
  ('da_vivere_lived-001', 1, 'da_vivere_lived', 'rivivete', 'open', 'Di «{title}», qual è il momento che ti è rimasto addosso?', '[]'::jsonb, 2, 'ctx_vissuta_momento', 'context', 'L’avete vissuta'),
  ('da_vivere_lived-002', 1, 'da_vivere_lived', 'rivivete', 'choice', 'Se potessimo rivivere «{title}» domani, cosa cambieresti?', '["Niente, rifarei tutto così","Solo il ritmo: più tempo","Tutto: un’esperienza nuova"]'::jsonb, 1, 'ctx_vissuta_rifarla', 'context', 'L’avete vissuta'),
  ('longitudinal-001', 1, 'longitudinal', null, 'open', '{previous_question}', '[]'::jsonb, 2, 'ctx_longitudinale', 'longitudinal', 'L’avete già giocata {when}'),
  ('moment-001', 1, 'moment', 'rivivete', 'open', 'Il ricordo «{title}», {when}: cosa stavi pensando in quel momento?', '[]'::jsonb, 2, 'ctx_ricordo_pensiero', 'context', 'Dai Ricordi'),
  ('moment-002', 1, 'moment', 'rivivete', 'open', 'Se il ricordo «{title}» avesse una colonna sonora, quale canzone sarebbe?', '[]'::jsonb, 1, 'ctx_ricordo_suono', 'context', 'Dai Ricordi')
on conflict (id) do nothing;
-- game-v2-recipes:end

-- ---------------------------------------------------------------------------
-- 2. Rendering helpers. Titles are sanitized before they can become a
--    question: one line, 3-60 characters, with letters, no links, no quotes
--    that would break the «…» framing.
-- ---------------------------------------------------------------------------

create function private.game_v2_clean_title(raw text)
returns text language sql immutable set search_path = '' as $$
  select case when t is null or char_length(t) not between 3 and 60 or t !~ '[[:alpha:]]'
      or t ~* '(https?://|www\.|[a-z0-9-]+\.(com|it|net|org)\y)' then null else t end
  from (select nullif(btrim(regexp_replace(translate(coalesce(raw, ''), '«»“”"', '     '), '\s+', ' ', 'g')), '') t) x;
$$;

create function private.game_v2_month_name(d date)
returns text language sql immutable set search_path = '' as $$
  select (array['gennaio', 'febbraio', 'marzo', 'aprile', 'maggio', 'giugno', 'luglio', 'agosto',
    'settembre', 'ottobre', 'novembre', 'dicembre'])[extract(month from d)::integer];
$$;

-- "a marzo", "ad aprile", "a marzo 2025" (year only when it differs).
create function private.game_v2_when_label(d date, at_date date)
returns text language sql immutable set search_path = '' as $$
  select case when extract(month from d) in (4, 8) then 'ad ' else 'a ' end || private.game_v2_month_name(d)
    || case when extract(year from d) <> extract(year from at_date) then ' ' || extract(year from d)::integer::text else '' end;
$$;

-- "12 ottobre".
create function private.game_v2_day_label(d date)
returns text language sql immutable set search_path = '' as $$
  select extract(day from d)::integer::text || ' ' || private.game_v2_month_name(d);
$$;

create function private.game_v2_fill(template text, source jsonb)
returns text language sql immutable set search_path = '' as $$
  select replace(replace(replace(replace(template,
    '{title}', coalesce(source->>'title', '')), '{date}', coalesce(source->>'date', '')),
    '{when}', coalesce(source->>'when', '')), '{previous_question}', coalesce(source->>'previous_question', ''));
$$;

-- Joins a set of source snapshots with the active recipes of one adapter.
-- Every candidate carries its provenance; the client shows only kind_label.
create function private.game_v2_recipe_candidates(target_family text, target_adapter text, source_kind text,
  sources jsonb, at_time timestamptz)
returns setof private.game_v2_candidate language sql stable set search_path = '' as $$
  select ('recipe:' || r.id || ':' || source_kind || ':' || (s->>'id')), r.family, r.mechanic, r.answer_kind,
    private.game_v2_fill(r.question_text, s), null::text, r.options, r.depth, r.topic, source_kind, s->>'id',
    r.id, r.version, null::uuid, null::integer,
    jsonb_build_object('kind', r.adapter, 'kind_label', private.game_v2_fill(r.kind_label, s),
      'source_type', source_kind, 'source_id', s->>'id', 'title', s->>'title', 'when', coalesce(s->>'when', s->>'date'),
      'recipe_id', r.id, 'recipe_version', r.version, 'captured_at', at_time),
    r.cooldown_class, 70 + 2 * (r.depth - 1), null::integer, null::boolean, null::timestamptz
  from jsonb_array_elements(coalesce(sources, '[]'::jsonb)) s
  join public.game_v2_recipes r on r.adapter = target_adapter and r.active
    and (target_family = 'per_voi' or r.family = target_family);
$$;

-- ---------------------------------------------------------------------------
-- 3. Explicit adapters. Each one is isolated: a failing source (schema drift,
--    unexpected data) is logged and skipped, never breaks a round. Sources
--    rotate weekly with a deterministic hash, at most four objects each.
-- ---------------------------------------------------------------------------

create function private.game_v2_ctx_da_vivere(target_couple uuid, target_family text, at_time timestamptz)
returns setof private.game_v2_candidate language plpgsql stable set search_path = '' as $$
declare ideas jsonb; lived jsonb; at_date date := (at_time at time zone 'Europe/Rome')::date;
  week text := private.game_v2_week_start(at_time)::text;
begin
  select coalesce(jsonb_agg(x.src), '[]'::jsonb) into ideas from (
    select jsonb_build_object('id', b.id::text, 'title', t.title) src
    from public.bucket_items b cross join lateral (select private.game_v2_clean_title(b.title) title) t
    where b.couple_id = target_couple and b.status in ('idea', 'scheduled') and t.title is not null
    order by md5(target_couple::text || ':' || b.id::text || ':' || week) limit 4) x;
  select coalesce(jsonb_agg(x.src), '[]'::jsonb) into lived from (
    select jsonb_build_object('id', b.id::text, 'title', t.title,
      'when', private.game_v2_when_label((b.completed_at at time zone 'Europe/Rome')::date, at_date)) src
    from public.bucket_items b cross join lateral (select private.game_v2_clean_title(b.title) title) t
    where b.couple_id = target_couple and b.status = 'lived' and t.title is not null
      and b.completed_at is not null
      and (b.completed_at at time zone 'Europe/Rome')::date between at_date - 730 and at_date - 3
    order by md5(target_couple::text || ':' || b.id::text || ':' || week) limit 4) x;
  return query select * from private.game_v2_recipe_candidates(target_family, 'da_vivere_idea', 'da_vivere', ideas, at_time);
  return query select * from private.game_v2_recipe_candidates(target_family, 'da_vivere_lived', 'da_vivere', lived, at_time);
exception when others then
  raise warning 'game_v2 context adapter da_vivere skipped: %', sqlerrm;
  return;
end;
$$;

create function private.game_v2_ctx_calendar(target_couple uuid, target_family text, at_time timestamptz)
returns setof private.game_v2_candidate language plpgsql stable set search_path = '' as $$
declare upcoming jsonb; past jsonb; at_date date := (at_time at time zone 'Europe/Rome')::date;
  week text := private.game_v2_week_start(at_time)::text;
begin
  -- Shared entries only; an entry already represented by a Da vivere item is
  -- left to that adapter so the same plan never appears twice.
  with shared as (
    select e.id, private.game_v2_clean_title(e.title) title,
      coalesce((e.starts_at at time zone 'Europe/Rome')::date, e.start_date) as on_day
    from public.calendar_entries e
    where e.couple_id = target_couple and e.entry_type = 'shared'
      and not exists (select 1 from public.bucket_items b where b.calendar_entry_id = e.id)
  )
  select
    coalesce((select jsonb_agg(x.src) from (
      select jsonb_build_object('id', s.id::text, 'title', s.title, 'date', private.game_v2_day_label(s.on_day)) src
      from shared s where s.title is not null and s.on_day between at_date + 1 and at_date + 60
      order by s.on_day, s.id limit 4) x), '[]'::jsonb),
    coalesce((select jsonb_agg(x.src) from (
      select jsonb_build_object('id', s.id::text, 'title', s.title, 'when', private.game_v2_when_label(s.on_day, at_date)) src
      from shared s where s.title is not null and s.on_day between at_date - 365 and at_date - 7
      order by md5(target_couple::text || ':' || s.id::text || ':' || week) limit 4) x), '[]'::jsonb)
  into upcoming, past;
  return query select * from private.game_v2_recipe_candidates(target_family, 'calendar_upcoming', 'calendar', upcoming, at_time);
  return query select * from private.game_v2_recipe_candidates(target_family, 'calendar_past', 'calendar', past, at_time);
exception when others then
  raise warning 'game_v2 context adapter calendar skipped: %', sqlerrm;
  return;
end;
$$;

create function private.game_v2_ctx_moments(target_couple uuid, target_family text, at_time timestamptz)
returns setof private.game_v2_candidate language plpgsql stable set search_path = '' as $$
declare src jsonb; at_date date := (at_time at time zone 'Europe/Rome')::date;
  week text := private.game_v2_week_start(at_time)::text;
begin
  select coalesce(jsonb_agg(x.src), '[]'::jsonb) into src from (
    select jsonb_build_object('id', m.id::text, 'title', t.title, 'when', private.game_v2_when_label(t.on_day, at_date)) src
    from public.moments m
    cross join lateral (select private.game_v2_clean_title(m.caption) title,
      coalesce(m.moment_date, (m.created_at at time zone 'Europe/Rome')::date) as on_day) t
    where m.couple_id = target_couple and t.title is not null and t.on_day between at_date - 730 and at_date - 14
    order by md5(target_couple::text || ':' || m.id::text || ':' || week) limit 4) x;
  return query select * from private.game_v2_recipe_candidates(target_family, 'moment', 'moment', src, at_time);
exception when others then
  raise warning 'game_v2 context adapter moments skipped: %', sqlerrm;
  return;
end;
$$;

-- Metadata only: whether the couple kept something recently. The kept items,
-- their sender and their text are never read.
create function private.game_v2_ctx_conservati(target_couple uuid, target_family text, at_time timestamptz)
returns setof private.game_v2_candidate language plpgsql stable set search_path = '' as $$
declare kept boolean;
begin
  select exists (select 1 from public.conserva_contributions c
    where c.couple_id = target_couple and c.created_at between at_time - interval '365 days' and at_time) into kept;
  if not kept then return; end if;
  return query select * from private.game_v2_recipe_candidates(target_family, 'conservati', 'conservati',
    jsonb_build_array(jsonb_build_object('id', 'conservati')), at_time);
exception when others then
  raise warning 'game_v2 context adapter conservati skipped: %', sqlerrm;
  return;
end;
$$;

-- Longitudinal resurfacing: a curated prompt marked longitudinal, answered
-- openly by both partners in a revealed round at least 90 days ago and not
-- played since, comes back as itself. The earlier answers are shown only in
-- the new reveal (see m11a_session_state below).
create function private.game_v2_ctx_longitudinal(target_couple uuid, target_family text, at_time timestamptz)
returns setof private.game_v2_candidate language plpgsql stable set search_path = '' as $$
declare at_date date := (at_time at time zone 'Europe/Rome')::date;
begin
  return query
  with plays as (
    select i.id item_id, i.source_ref catalog_id, s.started_at, s.completed_at,
      (select count(*) from public.game_session_answers a where a.item_id = i.id and a.answer_text is not null) answered
    from public.game_session_items i join public.game_sessions s on s.id = i.session_id
    where s.couple_id = target_couple and s.engine_version = 2 and i.source_type in ('curated', 'game_history')
  ), last_play as (
    select distinct on (p.catalog_id) p.catalog_id, p.started_at last_started from plays p
    order by p.catalog_id, p.started_at desc
  ), previous as (
    select distinct on (p.catalog_id) p.catalog_id, p.item_id, p.started_at, p.completed_at from plays p
    where p.completed_at is not null and p.answered = 2
    order by p.catalog_id, p.completed_at desc
  )
  select ('longitudinal:' || c.id), c.family, 'reciprocal'::text, 'open'::text,
    private.game_v2_fill(r.question_text, jsonb_build_object('previous_question', c.question_text)),
    null::text, '[]'::jsonb, c.depth, c.topic, 'game_history'::text, c.id, r.id, r.version, null::uuid, null::integer,
    jsonb_build_object('kind', 'longitudinal',
      'kind_label', private.game_v2_fill(r.kind_label, jsonb_build_object('when',
        private.game_v2_when_label((pv.started_at at time zone 'Europe/Rome')::date, at_date))),
      'source_type', 'game_history', 'source_id', c.id, 'previous_item_id', pv.item_id,
      'previous_played_at', pv.started_at, 'recipe_id', r.id, 'recipe_version', r.version, 'captured_at', at_time),
    r.cooldown_class, 72, null::integer, null::boolean, null::timestamptz
  from public.game_v2_catalog c
  join previous pv on pv.catalog_id = c.id
  join last_play lp on lp.catalog_id = c.id
  join public.game_v2_recipes r on r.adapter = 'longitudinal' and r.active
  where c.active and c.longitudinal and c.mechanic = 'reciprocal' and c.answer_kind = 'open'
    and (target_family = 'per_voi' or c.family = target_family)
    and lp.last_started <= at_time - interval '90 days'
  -- One resurfacing at a time: the prompt answered longest ago.
  order by pv.started_at, c.id
  limit 1;
exception when others then
  raise warning 'game_v2 context adapter longitudinal skipped: %', sqlerrm;
  return;
end;
$$;

-- The M11B plug-in point, now wired to the explicit adapters.
create or replace function private.game_v2_context_candidates(target_couple uuid, target_family text, at_time timestamptz)
returns setof private.game_v2_candidate language sql stable set search_path = '' as $$
  select * from private.game_v2_ctx_da_vivere(target_couple, target_family, at_time)
  union all select * from private.game_v2_ctx_calendar(target_couple, target_family, at_time)
  union all select * from private.game_v2_ctx_moments(target_couple, target_family, at_time)
  union all select * from private.game_v2_ctx_conservati(target_couple, target_family, at_time)
  union all select * from private.game_v2_ctx_longitudinal(target_couple, target_family, at_time);
$$;

revoke all on function private.game_v2_clean_title(text) from public, anon, authenticated;
revoke all on function private.game_v2_month_name(date) from public, anon, authenticated;
revoke all on function private.game_v2_when_label(date, date) from public, anon, authenticated;
revoke all on function private.game_v2_day_label(date) from public, anon, authenticated;
revoke all on function private.game_v2_fill(text, jsonb) from public, anon, authenticated;
revoke all on function private.game_v2_recipe_candidates(text, text, text, jsonb, timestamptz) from public, anon, authenticated;
revoke all on function private.game_v2_ctx_da_vivere(uuid, text, timestamptz) from public, anon, authenticated;
revoke all on function private.game_v2_ctx_calendar(uuid, text, timestamptz) from public, anon, authenticated;
revoke all on function private.game_v2_ctx_moments(uuid, text, timestamptz) from public, anon, authenticated;
revoke all on function private.game_v2_ctx_conservati(uuid, text, timestamptz) from public, anon, authenticated;
revoke all on function private.game_v2_ctx_longitudinal(uuid, text, timestamptz) from public, anon, authenticated;
revoke all on function private.game_v2_context_candidates(uuid, text, timestamptz) from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- 4. Reveal state with the longitudinal "then" (replaces the M11B body; same
--    signature). The earlier answers of a resurfaced prompt appear only once
--    the new round is revealed, and only from the same couple's own revealed
--    round, keyed by stable role (survives a re-pair).
-- ---------------------------------------------------------------------------

create or replace function private.m11a_session_state(target_session_id uuid, current_couple uuid, caller_role text)
returns jsonb language sql stable set search_path = '' as $$
  select jsonb_build_object(
    'id', s.id, 'couple_id', s.couple_id, 'game_family', s.game_family,
    'content_source', s.content_source, 'started_by_role', s.started_by_role,
    'started_at', s.started_at, 'completed_at', s.completed_at,
    'engine_version', s.engine_version, 'subject_heavy_role', s.subject_heavy_role,
    'my_role', caller_role,
    'my_complete', mine.completed_at is not null, 'my_completed_at', mine.completed_at,
    'partner_complete', partner.completed_at is not null, 'partner_completed_at', partner.completed_at,
    'reveal_ready', s.completed_at is not null, 'my_reveal_seen_at', mine.reveal_seen_at,
    'items', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', i.id, 'position', i.position, 'question_text', i.question_text,
        'answer_kind', i.answer_kind, 'options', i.options,
        'source_question_id', i.source_question_id, 'source_version', i.source_version,
        'mechanic', i.mechanic, 'family', coalesce(i.family, s.game_family),
        'subject_role', i.subject_role, 'predict_text', i.predict_text,
        'my_item_role', case when i.mechanic <> 'prediction' then 'mutual'
          when i.subject_role = caller_role then 'subject' else 'predictor' end,
        'my_prompt', case when i.mechanic = 'prediction' and i.subject_role <> caller_role
          then i.predict_text else i.question_text end,
        'source_type', i.source_type, 'depth', i.depth, 'context', i.context,
        'my_answer_text', a.answer_text, 'my_answer_index', a.answer_index,
        'partner_answer_text', case when s.completed_at is not null then pa.answer_text end,
        'partner_answer_index', case when s.completed_at is not null then pa.answer_index end,
        'prediction_matched', case when s.completed_at is not null and i.mechanic = 'prediction'
          and a.answer_index is not null and pa.answer_index is not null
          then a.answer_index = pa.answer_index end,
        'previous', case when s.completed_at is not null and i.context->>'kind' = 'longitudinal' then (
          select jsonb_build_object('played_at', ps.started_at,
            'my_answer_text', pma.answer_text, 'partner_answer_text', ppa.answer_text)
          from public.game_session_items pi
          join public.game_sessions ps on ps.id = pi.session_id
            and ps.couple_id = s.couple_id and ps.completed_at is not null
          left join public.game_session_answers pma on pma.item_id = pi.id and pma.actor_role = caller_role
          left join public.game_session_answers ppa on ppa.item_id = pi.id and ppa.actor_role <> caller_role
          where pi.id::text = i.context->>'previous_item_id') end
      ) order by i.position) from public.game_session_items i
      left join public.game_session_answers a on a.item_id = i.id and a.actor_role = caller_role
      left join public.game_session_answers pa on pa.item_id = i.id and pa.actor_role <> caller_role
      where i.session_id = s.id
    ), '[]'::jsonb)
  )
  from public.game_sessions s
  join public.game_session_sides mine on mine.session_id = s.id and mine.actor_role = caller_role
  join public.game_session_sides partner on partner.session_id = s.id and partner.actor_role <> caller_role
  where s.id = target_session_id and s.couple_id = current_couple;
$$;
revoke all on function private.m11a_session_state(uuid, uuid, text) from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- 5. Selector (replaces the M11B body; same signature). One change: a mode
--    round also keeps at least two curated or couple-authored prompts, so real
--    life never crowds out the editorial voice (Per voi keeps its cap of 2).
-- ---------------------------------------------------------------------------

create or replace function private.game_v2_select_items(target_couple uuid, target_family text, at_time timestamptz,
  round_ordinal integer)
returns jsonb language plpgsql stable set search_path = '' as $$
declare
  picked jsonb := '[]'::jsonb; keys text[] := '{}'; fams text[] := '{}'; topics text[] := '{}';
  sources text[] := '{}'; n_custom integer := 0; n_context integer := 0; n_pred integer := 0;
  n_deep integer := 0; n_light integer := 0;
  pass integer; seed integer; r private.game_v2_candidate;
  per_voi boolean := target_family = 'per_voi';
  fam_cap integer := case when target_family = 'per_voi' then 2 else 5 end;
begin
  for pass in 0..3 loop
    for seed in 1..3 loop
      exit when jsonb_array_length(picked) >= 5;
      continue when pass > 0 and seed > 1;
      continue when pass = 0 and not per_voi and seed < 3;
      for r in
        select * from private.game_v2_scored_candidates(target_couple, target_family, at_time, round_ordinal) c
        where (pass >= 2 or not c.cooled)
          and (pass <> 0 or (seed = 1 and c.source_type = 'couple_custom' and c.base_score >= 85)
                          or (seed = 2 and c.mechanic = 'prediction')
                          or (seed = 3 and c.depth = 1))
        order by case when pass >= 2 then c.last_played end asc nulls first, c.score desc, c.candidate_key
      loop
        exit when jsonb_array_length(picked) >= 5;
        continue when r.candidate_key = any (keys);
        continue when r.source_type <> 'curated' and (r.source_type || ':' || r.source_ref) = any (sources);
        continue when per_voi and r.mechanic = 'prediction' and n_pred >= 2;
        continue when per_voi and r.source_type = 'couple_custom' and n_custom >= 2;
        continue when r.source_type not in ('curated', 'couple_custom') and n_context >= case when per_voi then 2 else 3 end;
        if pass < 3 then
          continue when r.topic = any (topics);
          continue when (select count(*) from unnest(fams) f where f = r.family) >= fam_cap;
          continue when r.depth = 3 and n_deep >= 2;
          continue when r.depth = 1 and n_light >= 2;
        end if;
        picked := picked || jsonb_build_array(to_jsonb(r));
        keys := keys || r.candidate_key; fams := fams || r.family; topics := topics || r.topic;
        sources := sources || (r.source_type || ':' || r.source_ref);
        n_custom := n_custom + (r.source_type = 'couple_custom')::integer;
        n_context := n_context + (r.source_type not in ('curated', 'couple_custom'))::integer;
        n_pred := n_pred + (r.mechanic = 'prediction')::integer;
        n_deep := n_deep + (r.depth = 3)::integer;
        n_light := n_light + (r.depth = 1)::integer;
        exit when pass = 0;
      end loop;
    end loop;
  end loop;
  -- Lighter opening, meaningful middle, strongest later.
  return coalesce((select jsonb_agg(e order by (e->>'depth')::integer, (e->>'score')::integer, e->>'candidate_key')
    from jsonb_array_elements(picked) e), '[]'::jsonb);
end;
$$;
revoke all on function private.game_v2_select_items(uuid, text, timestamptz, integer) from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- 6. Perspective rotation. A prediction prompt played before comes back about
--    the other partner, inside the round's 3/2 subject split; the heavier
--    role still alternates across the couple's prediction rounds.
-- ---------------------------------------------------------------------------

create function private.game_v2_assign_subjects(target_couple uuid, items jsonb, heavy text)
returns jsonb language plpgsql stable set search_path = '' as $$
declare n integer; heavy_left integer; other_left integer; other text := private.game_v2_partner_role(heavy);
  subjects text[]; e jsonb; k integer := 0; pref text; alt integer := 0;
begin
  select count(*) into n from jsonb_array_elements(items) x where x->>'mechanic' = 'prediction';
  heavy_left := (n + 1) / 2; other_left := n / 2;
  subjects := array_fill(null::text, array[greatest(jsonb_array_length(items), 1)]);
  -- Pass 1: rotate the perspective of prompts the couple already played.
  for e in select value from jsonb_array_elements(items) loop
    k := k + 1;
    continue when e->>'mechanic' <> 'prediction';
    select private.game_v2_partner_role(i.subject_role) into pref
      from public.game_session_items i join public.game_sessions s on s.id = i.session_id
      where s.couple_id = target_couple and s.engine_version = 2 and i.fingerprint = e->>'candidate_key'
        and i.subject_role is not null
      order by s.started_at desc limit 1;
    if pref = heavy and heavy_left > 0 then subjects[k] := heavy; heavy_left := heavy_left - 1;
    elsif pref = other and other_left > 0 then subjects[k] := other; other_left := other_left - 1;
    end if;
  end loop;
  -- Pass 2: the rest alternate, heavy first, within the remaining split.
  k := 0;
  for e in select value from jsonb_array_elements(items) loop
    k := k + 1;
    continue when e->>'mechanic' <> 'prediction' or subjects[k] is not null;
    if (alt % 2 = 0 and heavy_left > 0) or other_left = 0 then subjects[k] := heavy; heavy_left := heavy_left - 1;
    else subjects[k] := other; other_left := other_left - 1; end if;
    alt := alt + 1;
  end loop;
  return (select coalesce(jsonb_agg(case when x.value->>'mechanic' = 'prediction'
      then x.value || jsonb_build_object('subject_role', subjects[x.ordinality::integer]) else x.value end
      order by x.ordinality), '[]'::jsonb)
    from jsonb_array_elements(items) with ordinality x);
end;
$$;
revoke all on function private.game_v2_assign_subjects(uuid, jsonb, text) from public, anon, authenticated;

-- start_game_round with the rotation (replaces the M11B body; same signature,
-- same locking, replay and resume contract).
create or replace function public.start_game_round(target_family text, request_id uuid)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare actor record; sid uuid; existing_family text; at_time timestamptz := private.game_v2_clock();
  ordinal integer; heavy text; items jsonb; e jsonb; pos integer := 0; subject text;
  sources text[]; source_kind text;
begin
  select * into actor from private.m11a_actor_locked();
  if request_id is null then raise exception using errcode = '22023', message = 'request id required'; end if;
  if target_family is null or not (target_family = 'per_voi' or target_family = any (private.game_v2_families())) then
    raise exception using errcode = '22023', message = 'invalid family';
  end if;

  select s.id, s.game_family into sid, existing_family from public.game_sessions s
    where s.couple_id = actor.caller_couple and s.started_by_role = actor.caller_role
      and s.create_request_id = start_game_round.request_id;
  if sid is not null then
    if existing_family is distinct from target_family then
      raise exception using errcode = '22023', message = 'request already used';
    end if;
    return private.m11a_session_state(sid, actor.caller_couple, actor.caller_role) || jsonb_build_object('resumed', true);
  end if;

  perform pg_advisory_xact_lock(hashtextextended('game_v2_round:' || actor.caller_couple::text || ':' || target_family, 0));
  select s.id into sid from public.game_sessions s
    where s.couple_id = actor.caller_couple and s.started_by_role = actor.caller_role
      and s.create_request_id = start_game_round.request_id and s.game_family = target_family;
  if sid is not null then
    return private.m11a_session_state(sid, actor.caller_couple, actor.caller_role) || jsonb_build_object('resumed', true);
  end if;
  select s.id into sid from public.game_sessions s
    where s.couple_id = actor.caller_couple and s.engine_version = 2 and s.game_family = target_family
      and s.completed_at is null;
  if sid is not null then
    return private.m11a_session_state(sid, actor.caller_couple, actor.caller_role) || jsonb_build_object('resumed', true);
  end if;

  select count(*) into ordinal from public.game_sessions s
    where s.couple_id = actor.caller_couple and s.engine_version = 2;
  select case when count(*) % 2 = 0 then 'beatrice' else 'francesco' end into heavy
    from public.game_sessions s
    where s.couple_id = actor.caller_couple and s.engine_version = 2 and s.subject_heavy_role is not null;

  items := private.game_v2_select_items(actor.caller_couple, target_family, at_time, ordinal);
  if jsonb_array_length(items) < 5 then
    raise exception using errcode = 'P0001', message = 'not enough content';
  end if;
  items := private.game_v2_assign_subjects(actor.caller_couple, items, heavy);
  select array_agg(distinct x->>'source_type' order by x->>'source_type') into sources from jsonb_array_elements(items) x;
  source_kind := case when sources = array['curated'] then 'curated'
    when sources = array['couple_custom'] then 'couple_custom' else 'mixed' end;

  -- started_at follows the server clock, like every cooldown that reads it.
  insert into public.game_sessions(couple_id, game_family, content_source, started_by_role, create_request_id,
    engine_version, subject_heavy_role, started_at)
  values (actor.caller_couple, target_family, source_kind, actor.caller_role, start_game_round.request_id, 2,
    case when exists (select 1 from jsonb_array_elements(items) x where x->>'mechanic' = 'prediction') then heavy end,
    at_time)
  returning id into sid;

  for e in select value from jsonb_array_elements(items) loop
    pos := pos + 1;
    subject := e->>'subject_role';
    insert into public.game_session_items(session_id, position, source_question_id, source_version,
      question_text, answer_kind, options, mechanic, subject_role, predict_text, family, source_type,
      source_ref, recipe_id, recipe_version, topic, perspective, depth, fingerprint, context)
    values (sid, pos, (e->>'source_question_id')::uuid, (e->>'source_version')::integer,
      private.game_v2_render(e->>'question_text', subject), e->>'answer_kind',
      private.game_v2_render_options(e->'options', subject), e->>'mechanic', subject,
      case when subject is not null then private.game_v2_render(e->>'predict_text', subject) end,
      e->>'family', e->>'source_type', e->>'source_ref', e->>'recipe_id', (e->>'recipe_version')::integer,
      e->>'topic', coalesce('subject:' || subject, 'mutual'), (e->>'depth')::smallint, e->>'candidate_key',
      coalesce(e->'context', '{}'::jsonb));
  end loop;
  insert into public.game_session_sides(session_id, actor_role) values (sid, 'francesco'), (sid, 'beatrice');
  return private.m11a_session_state(sid, actor.caller_couple, actor.caller_role) || jsonb_build_object('resumed', false);
end;
$$;

revoke all on function public.start_game_round(text, uuid) from public, anon;
grant execute on function public.start_game_round(text, uuid) to authenticated;
